      SUBROUTINE FILFRG (IPFS,I2FS,P,LM2F,PSA,JPSA,IPSA,NPSA,NORBS)
C     *
C     FILL SPARSE DENSITY MATRIX (PSA) WITH FRAGMENT DENSITY (P).
C     *
C     NOTATION. I=INPUT, O=OUTPUT.
C     IPFS      FIRST ORBITAL OF CURRENT FRAGMENT (I).
C     I2FS      FIRST DENSITY MATRIX ELEMENT OF CURRENT FRAGMENT (I).
C     P(LM2F,*) SQUARE DENSITY MATRIX OF FRAGMENT (I).
C     PSA       SPARSE DENSITY MATRIX OF MOLECULE (O).
C     JPSA      POINTERS FOR SPARSE MATRIX IN CSR FORMAT (O).
C     IPSA      COLUMN INDICES FOR SPARSE MATRIX IN CSR FORMAT (O).
C     NPSA      DIMENSION OF PSA AND JPSA (I).
C     NORBS+1   DIMENSION OF IPSA (I).
C     *
      IMPLICIT NONE
C     TYPE DECLARATIONS FOR ARGUMENTS.
C     POINTER ARRAYS FOR DENSITY MATRIX IN COMPRESSED ROW FORMAT.
      DOUBLE PRECISION, POINTER :: PSA(:)
      INTEGER, POINTER :: IPSA(:),JPSA(:)
      INTEGER IPFS,I2FS,LM2F,NPSA,NORBS
      DOUBLE PRECISION P(LM2F,LM2F)
C     TYPE DECLARATIONS FOR LOCAL VARIABLES.
      INTEGER I,IBASIS,J
C *** OUTER LOOP OVER ROWS OF FRAGMENT DENSITY MATRIX.
      DO 20 J=1,NORBS
      IPSA(IPFS-1+J) = I2FS + (J-1)*NORBS
      IBASIS = I2FS + (J-1)*NORBS - 1
C *** INNER LOOP OVER COLUMNS OF FRAGMENT DENSITY MATRIX.
      DO 10 I=1,NORBS
      PSA(IBASIS+I)  = P(I,J)
      JPSA(IBASIS+I) = IPFS + I - 1
   10 CONTINUE
   20 CONTINUE
      RETURN
      END
