      module module2
      INTERFACE
      SUBROUTINE CGDMSS (FS,PS,IFS,IPS,JFS,JPS,N,MPDIAG,NITER,NCG,PCGCRT,ICALL)
      USE module3
      IMPLICIT NONE
      INTEGER :: N,NITER,ICALL,NCG(10),MPDIAG,KEXT
      DOUBLE PRECISION :: PCGCRT
      DOUBLE PRECISION, DIMENSION (:), POINTER :: PS,FS
      INTEGER, DIMENSION (:), POINTER :: JPS,IPS,JFS,IFS
      END SUBROUTINE CGDMSS
!
      SUBROUTINE BORDS1 (DS,PS,PNS,IDS,IPS,IPNS,JDS,JPS,JPNS,PL,N,NITER,KEXT)
      USE module3
      IMPLICIT NONE
      INTEGER :: N,NITER,KEXT
      DOUBLE PRECISION PL
      DOUBLE PRECISION, DIMENSION (:), POINTER :: PS,DS,PNS
      INTEGER,          DIMENSION (:), POINTER :: IPS,JPS,IDS,JDS,IPNS,JPNS
      END SUBROUTINE BORDS1
!
      SUBROUTINE PONES (P,PS,IPS,JPS,LM6,N)
      IMPLICIT NONE
      INTEGER :: LM6,N
      DOUBLE PRECISION :: P(LM6)
      DOUBLE PRECISION, DIMENSION (:), POINTER :: PS
      INTEGER, DIMENSION (:), POINTER :: IPS,JPS
      END SUBROUTINE PONES
!
      SUBROUTINE PRTSCFS (FSA,PSA,IFSA,IPSA,JFSA,JPSA,N)
      USE module3
      IMPLICIT NONE
      INTEGER :: N
      DOUBLE PRECISION, DIMENSION (:), POINTER :: FSA,PSA
      INTEGER, DIMENSION (:), POINTER :: JFSA,IFSA,JPSA,IPSA
      END SUBROUTINE PRTSCFS
!
      SUBROUTINE SPARSP (PA,PPA,IIA,JJA,LM6,MPDIAG)
      USE LIMIT, ONLY: LM1, LMI, LMZ
      USE module3
      IMPLICIT NONE
      INTEGER :: LM6,MPDIAG
      DOUBLE PRECISION :: PPA(LM6)
      INTEGER, DIMENSION (:), POINTER :: IIA,JJA
      DOUBLE PRECISION, DIMENSION (:), POINTER :: PA
      END SUBROUTINE SPARSP
      END INTERFACE
      end module module2
