      SUBROUTINE SPAPRT (A,IIA,JJA,N)
C     *
C     PRINT SPARSE MATRIX STORED IN CSR FORMAT.
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     A(*)      NONZERO VALUES OF SPARSE MATRIX (I).
C     IIA(N+1)  POINTERS TO THE BEGINNING OF EACH ROW (I).
C     JJA(*)    COLUMN INDICES FOR NONZERO VALUES (I).
C     N         NUMBER OF ROWS (I).
C     *
C     IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      IMPLICIT NONE
      COMMON /NBFILE/ NBF(20)
      DOUBLE PRECISION, DIMENSION (:), POINTER ::A
      INTEGER, DIMENSION (:), POINTER :: IIA,JJA
      INTEGER N,I,K,NB6,NBF
C
      IF(IIA(N+1).LE.1 .OR. N.LE.0) RETURN
      NB6    = NBF(6)
      DO 10 K=1,N
      WRITE(NB6,500) K,IIA(K)
      WRITE(NB6,510) (JJA(I),A(I),I=IIA(K),IIA(K+1)-1)
   10 CONTINUE
      RETURN
  500 FORMAT(/1X,I5,' (ROW)      ',I5,' (POINTER)')
  510 FORMAT( 1X,I5,F12.5,I5,F12.5,I5,F12.5,I5,F12.5,I5,F12.5)
      END
