      SUBROUTINE XERALL (IERR,ROUTIN,ARRAY,N,MODE)
C     *
C     ERROR HANDLING ROUTINE FOR ALLOCATE AND DEALLOCATE.
C     PRINT APPROPRIATE MESSAGE AND STOP.
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     IERR      ERROR FLAG (I).
C     ROUTIN    NAME OF THE ROUTINE WHERE THE ERROR OCCURRED (I).
C     ARRAY     NAME OF THE ARRAY WHICH COULD NOT BE ALLOCATED (I).
C     N         REQUESTED SIZE OF THIS ARRAY (I).
C     MODE      TYPE OF ALLOCATION ERROR (I).
C               = 0 DURING ATTEMPT TO ALLOCATE MEMORY.
C               = 1 DURING ATTEMPT TO DEALLOCATE MEMORY.
C     *
C     IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      IMPLICIT NONE
      INTEGER N,IERR,NB6,MODE,NBF
      CHARACTER*(*) ROUTIN,ARRAY
      COMMON/NBFILE/ NBF(20)
      NB6 = NBF(6)
      IF(MODE.LE.0) THEN
         WRITE(NB6,500) IERR
      ELSE
         WRITE(NB6,510) IERR
      ENDIF
      WRITE(NB6,520) ROUTIN,ARRAY,N
      STOP 'XERALL'
  500 FORMAT(// 1X,'ERROR DURING MEMORY ALLOCATION, ERROR CODE =',I3)
  510 FORMAT(// 1X,'ERROR DURING MEMORY DEALLOCATION, ERROR CODE =',I3)
  520 FORMAT(/  1X,'ROUTINE: ',A,
     1       /  1X,'ARRAY  : ',A,
     2       /  1X,'SIZE   : ',I10,' WORDS'/)
      END
