      SUBROUTINE XERSPA (IERR,ROUTIN,CALLER,ID)
C     *
C     ERROR HANDLING ROUTINE FOR SPARSE ROUTINES.
C     PRINT APPROPRIATE MESSAGE AND STOP.
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     IERR      ERROR FLAG (I).
C     ROUTIN    NAME OF THE ROUTINE WHERE THE ERROR OCCURRED (I).
C     CALLER    NAME OF THE CALLING ROUTINE (I).
C     ID        IDENTIFIER OF CALL (I).
C     *
C     IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      IMPLICIT NONE
      INTEGER NB6,NBF,IERR,ID
      CHARACTER*(*) ROUTIN,CALLER
      COMMON/NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,500) IERR,ROUTIN,CALLER,ID
      STOP 'XERSPA'
  500 FORMAT(// 1X,'ERROR IN SPARSE MATRIX LIBRARY.',
     1       /  1X,'ERROR CODE : ',I6,
     2       /  1X,'SUBROUTINE : ',A,
     3       /  1X,'CALLED FROM: ',A,
     4       /  1X,'IDENTIFIER : ',I2/)
      END
