MODULE LIMIT

  IMPLICIT NONE

! PARAMETERS FOR THE SIZE OF THE PROGRAM.
! LEN      LENGTH OF BLANK COMMON (32-bit: 2**31-1, 64-bit: 2**63-1).
! LM1      MAXIMUM NUMBER OF ATOMS.
! LMI      MAXIMUM NUMBER OF UNIQUE AO PAIRS IN THE MOLECULE.
! LME      MAXIMUM NUMBER OF EXCHANGE  PAIRS IN THE MOLECULE.
! LMX      MAXIMUM NUMBER OF BASIS ORBITALS FOR INDEX ARRAY.
! LMV      MAXIMUM NUMBER OF GEOMETRICAL VARIABLES.
! LMS      MAXIMUM NUMBER OF SYMMETRY RELATIONS.
! LMGP     MAXIMUM NUMBER OF GAUSSIAN PRIMITIVES.
! LMGS     MAXIMUM NUMBER OF GAUSSIAN SHELLS.
! LMR      MAXIMUM NUMBER OF POINTS ON REACTION PATH (LMR).
! LMG      MAXIMUM NUMBER OF POINTS ON REACTION GRID (LMG,LMG).
! LMZ      MAXIMUM ATOMIC NUMBER.
! LMK      MAXIMUM NUMBER OF ECP OPERATORS.
! LML      MAXIMUM NUMBER OF ECP DATA SETS.
! LMF      MAXIMUM NUMBER OF REFERENCE DATA.
! LMFO     MAXIMUM NUMBER OF REFERENCE DATA IN PPFILES.
! LMM      MAXIMUM NUMBER OF REFERENCE MOLECULES.
! LMPR     MAXIMUM NUMBER OF REFERENCE PROPERTIES.
! LMMR     MAXIMUM NUMBER OF REFERENCE MOLECULES IN REACTION.
! LMP      MAXIMUM NUMBER OF PARAMETERS.
! LMNPS    MAXIMUM NUMBER OF SEGMENTS ON COSMO SURFACE.
! NPPA     MAXIMUM NUMBER OF COSMO GRID POINTS ON SPHERE.
! LM1M     MAXIMUM NUMBER OF EXTERNAL POINTS.
! MXNICS   MAXIMUM NUMBER OF NICS POINTS FOR NMR.
! LMACT    MAXIMUM NUMBER OF GUGA-CI ACTIVE MOS.
! LMREF    MAXIMUM NUMBER OF GUGA-CI REFERENCE CONFIGURATIONS.
! LMPROP   MAXIMUM NUMBER OF GUGA-CI PROPERTIES FOR CALREF.
! LMSTAT   MAXIMUM NUMBER OF GUGA-CI STATES FOR CALREF.
! LMGRD    MAXIMUM NUMBER OF GUGA-CI GRADIENT VECTORS.
! LMNAC    MAXIMUM NUMBER OF GUGA-CI NONADIABATIC COUPLING VECTORS.
! LMYL     MAXIMUM NUMBER OF YARKONY CI SEARCH LAGRANGE MULTIPLIERS.
! MAXGPU   MAXIMUM NUMBER OF GPUS THE PROGRAM IS PREPARED TO UTILIZE.

  INTEGER, PARAMETER :: LEN=2147483647
  INTEGER, PARAMETER :: LM1=1500
  INTEGER, PARAMETER :: LMI=45*LM1
  INTEGER, PARAMETER :: LME=81*LM1
  INTEGER, PARAMETER :: LMX=9*LM1
  INTEGER, PARAMETER :: LMV=3*LM1
  INTEGER, PARAMETER :: LMS=3*LM1
  INTEGER, PARAMETER :: LMGP=6*LM1
  INTEGER, PARAMETER :: LMGS=LM1
  INTEGER, PARAMETER :: LMR=200
  INTEGER, PARAMETER :: LMG=25
  INTEGER, PARAMETER :: LMZ=86
  INTEGER, PARAMETER :: LMK=200
  INTEGER, PARAMETER :: LML=100
  INTEGER, PARAMETER :: LMF=20000
  INTEGER, PARAMETER :: LMFO=3000
  INTEGER, PARAMETER :: LMM=10000
  INTEGER, PARAMETER :: LMPR=50
  INTEGER, PARAMETER :: LMMR=20
  INTEGER, PARAMETER :: LMP=200
  INTEGER, PARAMETER :: LMNPS=1000
  INTEGER, PARAMETER :: NPPA=1082
  INTEGER, PARAMETER :: LM1M=50000
  INTEGER, PARAMETER :: MXNICS=500
  INTEGER, PARAMETER :: LMACT=150
  INTEGER, PARAMETER :: LMREF=100
  INTEGER, PARAMETER :: LMPROP=17
  INTEGER, PARAMETER :: LMSTAT=40
  INTEGER, PARAMETER :: LMGRD=5
  INTEGER, PARAMETER :: LMNAC=10
  INTEGER, PARAMETER :: LMCONF=100000
  INTEGER, PARAMETER :: LMYL=5
  INTEGER, PARAMETER :: MAXGPU=8

END MODULE LIMIT
