      SUBROUTINE ADDGFX (H,LM4)
C     *
C     ADD CONSTANT GSBP CONTRIBUTION TO THE CORE MATRIX
C     F_MUNU -= 1/2 S_MUNU [ OMEGA_MU + OMEGA_NU ]
C     *
C     H(LM4)    CORE HAMILTONIAN MATRIX (I,O)
C     LM4       NUMBER OF BASIS FUNCTION PAIRS (I)
      USE LIMIT, ONLY: LM1, LMX, LMI
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./ATOMS / NUMAT,NAT(LM1),NFIRST(LM1),NLAST(LM1)
     ./INDEX / INDX(LMX)
     ./QMMM7 / GSBP1(LM1),GSBP2(LM1,LM1)
      DIMENSION H(LM4)

C *** DIAGONAL ELEMENTS OF ONE-ATOM TERMS.
      DO 10 I=1,NUMAT
      IA        = NFIRST(I)
      IB        = NLAST(I)
        DO 20 J=IA,IB
          LL      = INDX(J)+J
          H(LL)   = H(LL)-GSBP1(I)
   20   CONTINUE
   10 CONTINUE

      RETURN
      END


