      SUBROUTINE BONTYP (NI,NJ,NBOND)
C     *
C     ASSIGN BOND INDEX (NBOND) FOR A PAIR OF ELEMENTS (NI,NJ).
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION INMB(18)
      DATA INMB/1,0,0,0,2,3,4,5,6,0,0,0,0,7,8,9,10,0/
      JMAX   = MAX(INMB(NI),INMB(NJ))
      JMIN   = MIN(INMB(NI),INMB(NJ))
      NBOND  = (JMAX*(JMAX-1))/2+JMIN
      RETURN
      END
