      SUBROUTINE CLRGUG (A,LM5)
C     *
C     CLEAR (DEALLOCATE) GUGACI DATA AFTER CURRENT MOLECULE IS FINISHED.
C     *
C     ORIGINALLY, GUGACI DATA STRUCTURES WERE DEALLOCATED ONLY IF THE
C     INFORMATION THEREIN WAS OUTDATED, I.E. DUE TO A RELEVANT CHANGE
C     BETWEEN TWO GUGACI CALLS FOR THE SAME MOLECULE OR AT THE FIRST
C     CALL FOR A NEW MOLECULE. IN PARTICULAR GUGACI DATA WAS NOT FREED
C     AT THE END OF THE PROGRAM WHICH LOOKS LIKE A MEMORY LEAK TO A
C     MEMORY CHECKER MAKING TRUE LEAKS HARDER TO DETECT. DEALLOCATING
C     DATA STRUCTURES AFTER EACH MOLECULE MAY BE PREFERABLE BECAUSE
C     UNNEEDED MEMORY SHOULD BE FREED AS SOON AS POSSIBLE.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*8 DUMMY
      COMMON
     ./GUGA5 / MOLGUG,ICICAL,MULSAV
     ./INOPT2/ IN2(300)
     ./NBFILE/ NBF(20)
C *** FILE NUMBERS.
      NB6      = NBF(6)
C *** SAVE AND MODIFY INPUT FLAGS.
      IOUTCI   = IN2(133)
      IN2(133) = -9
C *** DUMMY ARGUMENTS.
      ICALL    =  0
      IZERO    =  0
      IONE     =  1
      MONE     = -1
      DUMMY    = 'DEADBEEF'
C *** TRIGGER GUGA-CI CLEANUP.
      ICALLG   =  7
      CALL GUGACI (ICALL,ICALLG,IONE,IONE,IONE,IONE,IONE,IONE,IONE,IONE,
     1             MONE,MONE,MONE,MONE,IZERO,IZERO,IONE,IZERO,NB6,IN2,
     2             DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,
     3             DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,
     4             DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,
     5             DUMMY,DUMMY,DUMMY,DUMMY,DUMMY,DUMMY)
C *** RESET INPUT FLAGS.
      IN2(133) = IOUTCI
C *** RESET FLAGS. THIS IS ESSENTIAL TO INDICATE A CLEANUP.
      MOLGUG   =  0
      ICICAL   =  0
      MULSAV   = -1
      END
