      SUBROUTINE CMOVE (A,B,N,LM2,LM3,FACTOR)
C     *
C     COPY ARRAY A(LM2,LM3) TO ARRAY B(LM2,LM3) AND MULTIPLY BY A
C     CONSTANT (FACTOR), FOR ROW AND COLUMN INDICES 1..N.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(LM2,LM3),B(LM2,LM3)
      DO 20 I=1,N
      DO 10 J=1,N
      B(J,I) = A(J,I)*FACTOR
   10 CONTINUE
   20 CONTINUE
      RETURN
      END
