      SUBROUTINE CODISK (A,B,LMA,LMB,MODE)
C     *
C     DISK INPUT/OUTPUT FOR COSMO WITH MINIMUM MEMORY OPTION.
C     *
C     NOTATION. I=INPUT, O=OUTPUT.
C     A(LMA)    INVERSE A-MATRIX FOR SURFACE CHARGE INTERACTIONS (I,O).
C     B(LMB)    B-MATRIX FOR SOLUTE/SURFACE INTERACTIONS (I,O).
C     MODE      CONTROL FLAG (0/1) FOR INPUT/OUTPUT.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./INOPT2/ IN2(300)
     ./NBFILE/ NBF(20)
      DIMENSION A(LMA),B(LMB)
C *** INITIALIZATION.
      ICOSMO = IN2(28)
      MODCSM = IN2(235)
      IF(ICOSMO.LE.0 .OR. MODCSM.LT.2) RETURN
C *** MODE.LE.0: READ ARRAYS A AND B FROM FILE NB17.
C     MODE.GT.0: WRITE ARRAYS A AND B TO FILE NB17.
      NB17   = NBF(17)
      REWIND NB17
      IF(MODE.LE.0) THEN
         READ(NB17) A,B
      ELSE
         WRITE(NB17) A,B
      ENDIF
      CLOSE(NB17)
      RETURN
      END
