      SUBROUTINE COMPFG (N,X,F,FBEST,G,ARRAY,LM5,ICALL,SCFCAL)
C     *
C     ROUTINE IN THE OPTIMIZATION SECTION THAT CALLS THE SCF SECTION.
C     *
C     NOTATION. I=INPUT,O=OUTPUT, S=SCRATCH.
C     N         NUMBER OF GEOMETRICAL VARIABLES (I).
C     X(N)      VALUES OF GEOMETRICAL VARIABLES (I).
C     F         CURRENT FUNCTION VALUE (O) - ENERGY OR GRADIENT NORM.
C     FBEST     BEST PREVIOUS FUNCTION VALUE (I).
C     G(N)      CURRENT GRADIENT (O).
C     ARRAY()   AVAILABLE BUFFER (I,O,S).
C     LM5       DIMENSION OF AVAILABLE BUFFER (I).
C     ICALL     CALLING CODE TO DEFINE TYPE OF CALCULATION (I),
C               NEGATIVE VALUE UPON RETURN SIGNALS AN ERROR (O).
C     SCFCAL    EXTERNAL ROUTINE FOR ENERGY EVALUATION (I).
C     *
      USE LIMIT, ONLY: LM1, LMV
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      EXTERNAL SCFCAL
      COMMON
     ./CYCLES/ ICYC,NCOUNT
     ./ERG   / ENERGY,GG(LMV),GNORM,CNORM
     ./ERG1  / CNORM1
     ./OVERLY/ IOV,JOV,KOV,LOV
C    ./INOPT1/ IN1(300)
     ./INOPT2/ IN2(300)
     ./PARM1 / A(LMV),NA(LM1,4),NATOMS
     ./PARM3 / LOC(LMV),NVAR3
     ./SKIPA / ISKPA
C    ./SCRT  / SCFCRT,PLCRT,SCFCRS,PLCRS
      DIMENSION G(N),X(N)
      DIMENSION ARRAY(LM5)
C     SAVE GNORMS
C     INPUT OPTIONS.
C     ISCRT  = IN1(35)+IN1(36)
C     IPREC  = IN2(43)
      JOP    = IN2(3)
      ICROSS = IN2(160)
C     MAKE CHANGES IN THE GEOMETRY.
      DO 10 I=1,N
      K      = LOC(I)
      A(K)   = X(I)
   10 CONTINUE
C     DEFINE THE PRESENT GEOMETRY.
      CALL SYMTRY(-1)
      CALL GMETRY(-1)
CSCF  REDEFINE THE SCF CONVERGENCE CRITERIA.
C     IF(ISCRT.LE.0 .AND. ISKPA.LE.0 .AND. ABS(IPREC).LE.1) THEN
C        SCFCRT = 1.0D-05
C        PLCRT  = 1.0D-03
C     ENDIF
CSCF  REDEFINE THE SCF CONVERGENCE CRITERIA IN AN ALTERNATIVE MANNER.
C     IF(ISCRT.LE.0 .AND. ISKPA.LE.0 .AND. (KOV.GT.0.OR.LOV.GT.1)) THEN
C        IF(GNORMS.GT.5.0D0) THEN
C           SCFCRT = MIN(SCFCRS*GNORMS*0.2D0,1.D-04)
C           PLCRT  = MIN(PLCRS *GNORMS*0.2D0,1.D-03)
C        ENDIF
C     ENDIF
C
C     CALL THE SCF PART.
      IF(ICROSS.LE.0) THEN
         JOV    = 1
         CALL SCF (ARRAY,LM5,ICALL,SCFCAL)
         IF(ICALL.EQ.-1) RETURN
         JOV    = 0
      ELSE IF(ICROSS.EQ.1 .OR. ICROSS.EQ.2 .OR. ICROSS.EQ.7) THEN
         CALL MULSTA (ARRAY,LM5,ICALL,SCFCAL)
         IF(ICALL.EQ.-1) RETURN
      ELSE
         CALL CONINT (ARRAY,LM5,ICALL,SCFCAL)
         IF(ICALL.EQ.-1) RETURN
      ENDIF
      IF(ICALL.LT.22) NCOUNT=NCOUNT+1
C
C     RESET FLAG FOR FAST DIAGONALIZATION (IFAST).
      IF(IN2(73).EQ.0) IN2(73)=-1
CSCF  RESET THE SCF CONVERGENCE CRITERIA.
C     SCFCRT = SCFCRS
C     PLCRT  = PLCRS
C     AFTER THE CALL TO SUBROUTINE SCF, COMMON BLOCK /ERG/ CONTAINS
C     FOR                                            ICALL   ISKPA
C     ENERGY = CURRENT ENERGY                     10,20,21    0,1
C     GG(I)  = CURRENT GRADIENT                      21,22    0,1
C     GNORM  = CURRENT GRADIENT NORM FOR GG(I)       21,22    0,1
C     CNORM  = CURRENT CARTESIAN GRADIENT NORM       21,22    0
C     STORE FUNCTION VALUE AND GRADIENTS.
      F      = ENERGY
      IF(ICALL.GT.20) THEN
         FUN    = GNORM*GNORM
         DO 20 I=1,N
         G(I)   = GG(I)
         IF(ABS(G(I)).LT.1.0D-06) G(I)=1.0D-06
   20    CONTINUE
         IF(JOP.EQ.1 .OR. JOP.EQ.4 .OR. JOP.EQ.6) F=FUN
         IF(F.LE.FBEST .AND. ISKPA.LE.0) CNORM1=CNORM
C        GNORMS = GNORM
      ENDIF
      RETURN
      END
