      SUBROUTINE CORGAU (ISHELL,JSHELL,NI,NJ,R,CORT)
C     *
C     ANALYTICAL TWO-CENTER CORE-ELECTRON ATTRACTIONS (IN EV).
C     *
C     NOTATION.  I=INPUT, O=OUTPUT.
C     ISHELL     SHELL NUMBER (I).
C     JSHELL     SHELL NUMBER (I).
C     NI,NJ      ATOMIC NUMBERS (I).
C     R          DISTANCE BETWEEN ATOMS I-J IN AU (I).
C     CORT       CORE-ELECTRON ATTRACTION INTEGRALS IN EV (O).
C     *
      USE LIMIT, ONLY: LMZ
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./CONSTF/ A0,AFACT,EV,EVCAL,PI,W1,W2,BIGEXP
     ./PARDER/ TORE(LMZ),EHEAT(LMZ),EISOL(LMZ)
C    ./CONSTN/ ZERO,ONE,TWO,THREE,FOUR,PT5,PT25
      DIMENSION CORT(10,2)
C *** INITIALIZATION.
C     DO 10 I=1,4
C     CORT(I,1) = ZERO
C  10 CORT(I,2) = ZERO
C *** CONVENTIONS. ATOM I IN ORIGIN, ATOM J ON POSITIVE Z-AXIS.
C     IATOM=1   ELECTRONS OF ATOM I, CORE      OF ATOM J.
C     IATOM=2   CORE      OF ATOM I, ELECTRONS OF ATOM J.
C *** INTEGRALS IN LOCAL COORDINATES.
      CALL CORGTO (ISHELL,ITYP,R,CORT(1,1))
      CALL CORGTO (JSHELL,JTYP,R,CORT(1,2))
C *** CONVERT AND STORE THE INTEGRALS.
      FI     = - TORE(NI)*EV
      FJ     = - TORE(NJ)*EV
      CORT(1,1) = CORT(1,1)*FJ
      CORT(1,2) = CORT(1,2)*FI
      IF(ITYP.GT.0) THEN
         CORT(2,1) = CORT(2,1)*FJ
         CORT(3,1) = CORT(3,1)*FJ
         CORT(4,1) = CORT(4,1)*FJ
      ENDIF
      IF(JTYP.GT.0) THEN
         CORT(2,2) =-CORT(2,2)*FI
         CORT(3,2) = CORT(3,2)*FI
         CORT(4,2) = CORT(4,2)*FI
      ENDIF
      RETURN
      END
