      SUBROUTINE DYNDEF
C     *
C     INITIALIZATION FOR DYNAMIC MEMORY ALLOCATION.
C     *
C     THE FOLLOWING COMMON BLOCK VARIABLES ARE DEFINED PROPERLY.
C     INDEX : INDX(LMX)
C     LIMITS: LM2,LM3,LM4,LM6
C     LMCSM2: LMQ=LMC1(6)
C     *
C     THE ADDRESSES IN THE FOLLOWING COMMON BLOCKS ARE INITIALIZED.
C     GUGA2, LMCSM1, LMCSM2, LMDIIS, LMDMS, LMFOR, LMGRAD, LMSCF, LMUHF.
C     *
      USE LIMIT, ONLY: LM1, LMX
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./ATOMS / NUMAT,NAT(LM1),NFIRST(LM1),NLAST(LM1)
     ./GUGA2 / LCI1(2)
     ./INDEX / INDX(LMX)
     ./INOPT2/ IN2(300)
     ./LIMITS/ LM2,LM3,LM4,LM6,LM7,LM8,LM9
     ./LMCSM1/ LC1(4)
     ./LMCSM2/ LMC1(7)
     ./LMDIIS/ LDIIS1(9)
     ./LMDMS / LD1(5)
     ./LMFOR / LF1(8),LFA
     ./LMGRAD/ LG1(8)
     ./LMPERT/ LP1(5)
     ./LMSCF / LS1(9)
     ./LMUHF / LU1(8)
     ./ORBITS/ NUMB,NORBS,NMOS,NALPHA,NBETA
C     *
C *** DEFINE SIZE OF MATRICES USED IN SCF CALCULATION.
      LM2    = NORBS
      LM3    = LM2
      LM4    = (NORBS*(NORBS+1))/2
      IF(MOD(LM2,16).EQ.0) LM2=NORBS+1
C     *
C *** DEFINE INDEX ARRAY.
      DO 10 I=1,NORBS
      INDX(I)= I*(I-1)/2
   10 CONTINUE
C     *
C *** DEFINE NUMBER OF UNIQUE ONE-CENTER AO PAIRS.
      LM6    = 0
      DO 20 I=1,NUMAT
      ITEMP  = NLAST(I)-NFIRST(I)+1
      LM6    = LM6+INDX(ITEMP)+ITEMP
   20 CONTINUE
      IF(IN2(2).GT.1) LM6=NUMAT
C     *
C *** INITIALIZE ADDRESS POINTERS FOR VARIOUS ARRAYS.
C     THIS AVOIDS CALLS WITH UNDEFINED ADDRESSES IN CASES
C     WHERE THE CORRESPONDING OPTIONS ARE NOT USED.
      DO 30 I=1,4
      LC1(I) = 1
   30 CONTINUE
      DO 40 I=1,7
      LMC1(I)= 1
   40 CONTINUE
      DO 50 I=1,5
      LD1(I) = 1
   50 CONTINUE
      DO 60 I=1,8
      LF1(I) = 1
   60 CONTINUE
      DO 70 I=1,8
      LG1(I) = 1
   70 CONTINUE
      DO 80 I=1,5
      LP1(I) = 1
   80 CONTINUE
      DO 90 I=1,9
      LS1(I) = 1
   90 CONTINUE
      DO 100 I=1,8
      LU1(I) = 1
  100 CONTINUE
      DO 110 I=1,9
      LDIIS1(I) = 1
  110 CONTINUE
      DO 120 I=1,2
      LCI1(I) = 1
  120 CONTINUE
C     *
C *** DEFINE NUMBER OF SOLUTE CHARGES FOR COSMO TREATMENT.
C     LMC1(6) = LMQ
      LMC1(6) = LM6+NUMAT
      RETURN
      END
