      SUBROUTINE FMATRX (A,LM5,ICALL,SCFCAL,I3N)
C     *
C     DRIVER ROUTINE FOR CALCULATION OF FORCE CONSTANTS.
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     A(LM5)    AVAILABLE BUFFER (S).
C     ICALL     CONTROL AND ERROR FLAG (O,S).
C     SCFCAL    EXTERNAL ROUTINE FOR ENERGY EVALUATION (I).
C     I3N       DIMENSION OF FORCE CONSTANT MATRIX (3*NUMAT).
C     *
C     ICALL=0   INITIAL VALUE UPON INPUT.
C     ICALL>0   INTERNAL CONTROL IN WORKING ROUTINES (S).
C     ICALL<0   ERROR FLAG (O).
C     ICALL=-2  NO SCF CONVERGENCE.
C     ICALL=-7  GRADIENT AT INPUT GEOMETRY TOO HIGH (ONLY JOP=5,6).
C     ICALL=-8  TIME LIMIT.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      EXTERNAL SCFCAL
      COMMON
     ./INOPT2/ IN2(300)
     ./LMFOR / LF1,LF2,LF3,LF4,LF5,LF6,LF7,LF8,LFA
     ./SKIPAF/ ISKPAF
      DIMENSION A(LM5)
C *** INITIALIZATION.
      JOP    = IN2(3)
      MPLIB  = IN2(7)
      LMA    = I3N*I3N
      LMAPT  = I3N*3
      IF(JOP.LT.2) RETURN
C *** CALL WORKING ROUTINES.
C     FMTRXA : ANALYTICAL EVALUATION FOR VARIATIONAL METHODS.
C     FMTRX  : FINITE-DIFFERENCE EVALUATION FROM GRADIENTS.
C     FMTRXP : PARALLEL VERSION OF FMTRX.
      IF(ISKPAF.EQ.-2) THEN
         CALL FMTRXA(A(LF1),A(LF3),LMA,LMAPT,A,LM5,ICALL,SCFCAL)
      ELSE IF(MPLIB.GE.0) THEN
         CALL FMTRX (A(LF1),A(LF3),LMA,LMAPT,A,LM5,ICALL,SCFCAL)
      ELSE
         CALL FMTRXP(A(LF1),A(LF3),LMA,LMAPT,A,LM5,ICALL,SCFCAL)
      ENDIF
C *** ERROR EXIT: NO SCF CONVERGENCE.
      IF(ICALL.EQ.-1) ICALL=-2
C *** ERROR EXIT: GRADIENT TOO HIGH.
      IF(ICALL.EQ.-7 .AND. IN2(37).GT.0) IN2(37)=0
      RETURN
      END
