      SUBROUTINE GCRGDR (A,LM5,LMA,PA,PB,CA,CB,LM2,EA,EB,LMF)
C     *
C     COMPUTE AND PRINT ATOMIC DERIVATIVES OF
C     MULLIKEN CHARGES FOR GSBP GRADIENT
C
C     *
C     A         SCRATCH (I,O)
C     LM5       DIMENSION OF A (I)
C     LMA       DIMENSION OF FORCE CONSTANT MATRIX
C     PA        ALPHA DENSITY MATRIX PACKED (I)
C     PB        BETA DENSITY MATRIX PACKED (I)
C     CA        ALPHA ORBITAL COEFFICIENTS (I)
C     CB        BETA ORBITAL COEFFICIENTS (I)
C     LM2       NUMBER OF ORBITALS (I)
C     EA        ALPHA ORBITAL ENERGIES (I)
C     EB        BETA ORBITAL ENERGIES (I)
C     LMF       DIMENSIONS OF DERIVATIVE MATRIX

      USE LIMIT, ONLY: LM1, LMX, LMV
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./ATOMS / NUMAT,NAT(LM1),NFIRST(LM1),NLAST(LM1)
     ./ORBITS/ NUMB,NORBS,NMOS,NALPHA,NBETA
     ./INDEX / INDX(LMX)
     ./CONSTN/ ZERO,ONE,TWO,THREE,FOUR,PT5,PT25
      DIMENSION A(LM5),GRAD(2),DUM(2),FMTRX(LMA)
      DIMENSION CRGDRV(LMF,NUMAT)
      DIMENSION CA(LM2,LM2),CB(LM2,LM2),EA(LM2),EB(LM2)

C     WRITE(*,*) "CALCULATE MULLIKEN CHARGE DERIVATIVES!"

C     GET MULLIKEN CHARGE DERIVATIVES
C     USE MODIFIED VERSION OF PSDRV ROUTINE

      CALL PSGSBP(2,GRAD,FMTRX,DUM,LMF,A,LM5,PA,PB,CA,CB,
     .           LM2,EA,EB,CRGDRV)

C     DO 20 I=1,LMF
C         WRITE(*,*) (CRGDRV(I,J),J=1,NUMAT)
C  20 CONTINUE

C     PRINT LINEAR DERIVATIVES TO FILE
      NB88 = 88
      OPEN (NB88, FILE='mndo.gsbp.crgdrv', STATUS= 'UNKNOWN')

      DO 30 I=1,NUMAT
        DO 40 J=1,3
          WRITE(NB88,*) CRGDRV((I-1)*3+J,I)
   40   CONTINUE
   30 CONTINUE
      CLOSE(NB88)

C     ALSO PRINT COUPLED DERIVATIVES TO FILE
      OPEN (NB88, FILE='mndo.gsbp.cpcrgdrv', STATUS= 'UNKNOWN')
      DO 50 I=1,LMF
        WRITE(NB88,*) (CRGDRV(I,J),J=1,NUMAT)
   50 CONTINUE
      CLOSE(NB88)


      RETURN
      END


