      SUBROUTINE GETVAL (LINE,X,T)
C     *
C     ANALYZE INPUT STRING LINE (NUMERIC DATA OR CHARACTER DATA)
C     AND RETURN EITHER NUMERIC VALUE IN X OR NON-BLANK STRING IN T.
C     ADAPTED FROM MOPAC(6.0) WRITTEN BY J.J.P.STEWART.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER LINE*(*), T*12, CH1*1, CH2*1
      CH1    = LINE(1:1)
      CH2    = LINE(2:2)
      IF((ICHAR(CH1).LT.ICHAR('A').OR.ICHAR(CH1).GT.ICHAR('Z')) .AND.
     1   (ICHAR(CH2).LT.ICHAR('A').OR.ICHAR(CH2).GT.ICHAR('Z')))THEN
         X=READA(LINE,1,0)
         T=' '
      ELSE
         I=INDEX(LINE,' ')
         T=LINE(:I)
         X=-999.0D0
      ENDIF
      RETURN
      END
