      SUBROUTINE INGSBP
C     *
C     READ GSBP MATRICES OMEGA AND GAMMA FROM FILE.
C     *
      USE LIMIT, ONLY: LM1
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./ATOMS / NUMAT,NAT(LM1),NFIRST(LM1),NLAST(LM1)
     ./LIMITS/ LM2,LM3,LM4,LM6,LM7,LM8,LM9
     ./QMMM7 / GSBP1(LM1),GSBP2(LM1,LM1)
        WRITE(*,*) "GSBP OMEGA MATRIX"
C     READ OMEGA MATRIX FIRST
      NB88 = 88
      OPEN (NB88, FILE='mndo.gsbp.omega', STATUS= 'UNKNOWN')

C     READ FROM FILE
      DO 10 I=1,NUMAT
        READ(NB88,*) GSBP1(I)
   10 CONTINUE
      CLOSE(NB88)

C     READ GAMMA MATRIX NOW
      OPEN (NB88, FILE='mndo.gsbp.gamma', STATUS= 'UNKNOWN')
      DO 30 I=1,NUMAT
        READ(NB88,*) (GSBP2(I,J),J=1,NUMAT)
   30 CONTINUE
      CLOSE(NB88)

      RETURN
      END


