      SUBROUTINE KEYDOC (LM96,LM96X,LMMO1,LMMO2,LMMO3,KEY96,KEY96X,
     1      KEYMO1,KEYMO2,KEYMO3,LEN96,LEN96X,LENMO1,LENMO2,LENMO3,
     2      TXTMO1,TXTMO2,TXTMO3,IN1MO1,IN1MO2,IN1MO3,INVMO1)
C     *
C     DOCUMENTATION OF THE AVAILABLE KEYWORDS.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*6   KEY96,KEY96X
      CHARACTER*7   KEYMO1,KEYMO2,KEYMO3
      CHARACTER*60  TXTMO1,TXTMO2,TXTMO3
      COMMON /NBFILE/ NBF(20)
      DIMENSION KEY96(LM96),LEN96(LM96)
      DIMENSION KEY96X(LM96X),LEN96X(LM96X)
      DIMENSION KEYMO1(LMMO1),KEYMO2(LMMO2),KEYMO3(LMMO3)
      DIMENSION LENMO1(LMMO1),LENMO2(LMMO2),LENMO3(LMMO3)
      DIMENSION TXTMO1(LMMO1),TXTMO2(LMMO2),TXTMO3(LMMO3)
      DIMENSION IN1MO1(LMMO1),IN1MO2(LMMO2),IN1MO3(LMMO3)
      DIMENSION INVMO1(LMMO1)
C     *
C *** NOTATION.
C     *
C     KEY96(I) ALLOWS TO SIMULATE THE NUMERICAL INPUT TO MNDO96
C     BY USING KEYWORDS IN MOPAC-STYLE: INTEGER INPUT.
C     LEN96(I) IS THE LENGTH OF THE STRING DEFINING KEY96(I).
C     *
C     KEY96X(I) ALLOWS TO SIMULATE THE NUMERICAL INPUT TO MNDO96
C     BY USING KEYWORDS IN MOPAC-STYLE: DECIMAL INPUT.
C     LEN96X(I) IS THE LENGTH OF THE STRING DEFINING KEY96X(I).
C     *
C     KEYMO1(I) CONTAINS MOPAC-TYPE KEYWORDS WITHOUT = ...
C     NO ADDITIONAL NUMERICAL INPUT ASSOCIATED WITH THE KEYWORD.
C     LENMO1(I) IS THE LENGTH OF THE STRING DEFINING KEYMO1(I).
C     IN1MO1(I): INDEX J OF OPTION IN1(J) ASSOCIATED WITH KEYMO1(I).
C     INVMO1(I): VALUE  FOR OPTION IN1(J) ASSOCIATED WITH KEYMO1(I).
C     TXTMO1(I) CONTAINS DESCRIPTIVE TEXT ASSOCIATED WITH KEYMO1(I).
C     *
C     KEYMO2(I) CONTAINS MOPAC-TYPE KEYWORDS WITH = (INTEGER).
C     THERE IS ADDITIONAL INTEGER INPUT ASSOCIATED WITH THE KEYWORD.
C     LENMO2(I) IS THE LENGTH OF THE STRING DEFINING KEYMO2(I).
C     IN1MO2(I): INDEX J OF OPTION IN1(J) ASSOCIATED WITH KEYMO2(I).
C     TXTMO2(I) CONTAINS DESCRIPTIVE TEXT ASSOCIATED WITH KEYMO2(I).
C     *
C     KEYMO3(I) CONTAINS MOPAC-TYPE KEYWORDS WITH = (REAL).
C     THERE IS ADDITIONAL REAL INPUT ASSOCIATED WITH THE KEYWORD.
C     LENMO3(I) IS THE LENGTH OF THE STRING DEFINING KEYMO3(I).
C     IN1MO3(I): INDEX J OF OPTION IN1(J) ASSOCIATED WITH KEYMO3(I).
C     TXTMO3(I) CONTAINS DESCRIPTIVE TEXT ASSOCIATED WITH KEYMO3(I).
C     *
C *** FILE NUMBERS.
      NB6    = NBF(6)
C *** LOOP OVER STANDARD KEYWORDS WITH INTEGER INPUT.
      WRITE(NB6,300)
      WRITE(NB6,400)
      WRITE(NB6,450)
      DO 20 I=1,LM96
      WRITE(NB6,500) I,KEY96(I),LEN96(I),I
   20 CONTINUE
C *** LOOP OVER STANDARD KEYWORDS WITH REAL INPUT.
      WRITE(NB6,405)
      WRITE(NB6,460)
      DO 30 I=1,LM96X
      WRITE(NB6,500) I,KEY96X(I),LEN96X(I),I
   30 CONTINUE
C *** LOOP OVER MOPAC-TYPE KEYWORDS WITHOUT NUMERICAL INPUT.
      WRITE(NB6,410)
      WRITE(NB6,440)
      DO 40 I=1,LMMO1
      L      = LENMO1(I)
      WRITE(NB6,510) I,KEYMO1(I),L,IN1MO1(I),INVMO1(I),TXTMO1(I)(5:)
   40 CONTINUE
C *** LOOP OVER MOPAC-TYPE KEYWORDS WITH INTEGER INPUT.
      WRITE(NB6,420)
      WRITE(NB6,450)
      DO 50 I=1,LMMO2
      L      = LENMO2(I)
      WRITE(NB6,520) I,KEYMO2(I),L,IN1MO2(I),TXTMO2(I)(5:)
   50 CONTINUE
C *** LOOP OVER MOPAC-TYPE KEYWORDS WITH REAL INPUT.
      WRITE(NB6,430)
      WRITE(NB6,460)
      DO 60 I=1,LMMO3
      L      = LENMO3(I)
      WRITE(NB6,520) I,KEYMO3(I),L,IN1MO3(I),TXTMO3(I)(5:)
   60 CONTINUE
      RETURN
  300 FORMAT(///1X,'DOCUMENTATION OF AVAILABLE KEYWORDS.')
  400 FORMAT(///1X,'STANDARD KEYWORDS WITH INTEGER INPUT.'/)
  405 FORMAT(///1X,'STANDARD KEYWORDS WITH REAL INPUT.'/)
  410 FORMAT(///1X,'MOPAC6 KEYWORDS WITHOUT NUMERICAL INPUT.'/)
  420 FORMAT(///1X,'MOPAC6 KEYWORDS WITH INTEGER INPUT.'/)
  430 FORMAT(///1X,'MOPAC6 KEYWORDS WITH REAL INPUT.'/)
  440 FORMAT(   1X,'                 LEN  IN2 VALUE')
  450 FORMAT(   1X,'                 LEN  IN2')
  460 FORMAT(   1X,'                 LEN  XN2')
  500 FORMAT(1X,I3,4X,A6,4X,I2,3X,I3)
  510 FORMAT(1X,I3,4X,A7,3X,I2,3X,I3,I4,4X,A)
  520 FORMAT(1X,I3,4X,A7,3X,I2,3X,I3,3X,A)
      END
