      SUBROUTINE MPCPOP (POPI,QI,NUMAT,NB16,MUL)
C     *
C     WRITE MULLIKEN POPULATIONS AND CHARGES
C     ON SYBYL OUTPUT FILE NB16 ACCORDING TO MOPAC CONVENTIONS.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /NBFILE/ NBF(20)
      DIMENSION POPI(NUMAT),QI(NUMAT)
      WRITE(NB16,500,ERR=20) MUL
      IF(MUL.EQ.0) RETURN
      DO 10 I=1,NUMAT
      WRITE(NB16,510,ERR=20) POPI(I),QI(I)
   10 CONTINUE
      RETURN
C *** ERROR EXIT.
   20 CONTINUE
      NB6 = NBF(6)
      WRITE(NB6,520)
      RETURN
  500 FORMAT(I4,5X,' MULLIKEN POPULATION AND CHARGE')
  510 FORMAT(2F12.6)
  520 FORMAT(1X,'Error writing SYBYL Mulliken population output')
      END
