      SUBROUTINE OM2SAV (NB,A,LM5,MODE)
C     *
C     SAVE OM2 MATRICES ON   FILE NF (MODE=0).
C     READ OM2 MATRICES FROM FILE NF (MODE=1).
C     *
C     CONVENTION FOR THE FILE NUMBER NF:
C     NF=NB      FOR NB.GT.0, THE FILE IS REWOUND.
C     NF=NBF(18) FOR NB.EQ.0, THE FILE IS REWOUND.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./LMGRAD/ LG1,LG2,LG3,LG4,LG5,LG6,LG7,LG8
     ./NBFILE/ NBF(20)
      DIMENSION A(LM5)
      IF(NB.GT.0) THEN
         NF  = NB
      ELSE
         NF  = NBF(18)
      ENDIF
      REWIND NF
      IF(MODE.EQ.0) THEN
         WRITE(NF) (A(I),I=LG1,LG5-1)
      ELSE IF(MODE.EQ.1) THEN
         READ (NF) (A(I),I=LG1,LG5-1)
      ENDIF
      RETURN
      END
