      SUBROUTINE PAROUT (IOP,NMR,NI)
C     *
C     PRINT THE PARAMETERS USED FOR ELEMENT NI.
C     *
      USE LIMIT, ONLY: LMZ
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (LMPAR=81)
      PARAMETER (ZERO=0.0D0)
      CHARACTER PARTYP(LMPAR)*5
      CHARACTER UNIT  (LMPAR)*48
      CHARACTER UNIT3G*48
      CHARACTER UNIT4G*48
      COMMON
     ./ABOND / ALPB(LMZ,LMZ),MALPB(LMZ)
     ./AMPGAU/ GUESS1(LMZ,4),GUESS2(LMZ,4),GUESS3(LMZ,4),GSCAL(LMZ),
     .         IMP(LMZ)
     ./DIPOL1/ HYF(LMZ),HYFPD(LMZ)
     ./DPARM / LORBS(LMZ)
     ./DPARM1/ UDD(LMZ,3)
     ./DPARM2/ ZSN(LMZ,3)
     ./DPARM3/ F0DD(LMZ,9)
     ./INOPT2/ IN2(300)
     ./MULTIP/ DD(6,0:LMZ),PO(9,0:LMZ)
     ./NBFILE/ NBF(20)
     ./PARDER/ CORE(LMZ),EHEAT(LMZ),EISOL(LMZ)
     ./PAROPT/ USS(LMZ,7)
     ./PAROMM/ OMM(LMZ,16)
     ./PDDG1 / DA(LMZ,2),PA(LMZ,2)
     ./PSNPRD/ XBETAN(LMZ,3),XZETAN(LMZ,3),XZETAS(LMZ,3),XBETAS(LMZ,3),
     .         XUS(LMZ,3),XSCALN(0:LMZ),XOFFN(0:LMZ,2),IDEFN(0:LMZ)
     ./REP   / GSS(LMZ,6)
C *** NUMBERING OF PARAMETERS FOR PRINTING PURPOSES.
C      1 USS  ,  2 UPP  ,  3 ZS   ,  4 ZP   ,  5 BETAS,  6 BETAP,
C      7 ALP  ,  8 GSS  ,  9 GPP  , 10 GSP  , 11 GP2  , 12 HSP  ,
C     13 UDD  , 14 ZD   , 15 BETAD, 16 ZSN  , 17 ZPN  , 18 ZDN  ,
C     19 F0DD , 20 F2DD , 21 F4DD , 22 F0SD , 23 G2SD , 24 F0PD ,
C     25 F2PD , 26 G1PD , 27 G3PD , 28 DD2  , 29 DD3  , 30 DD4  ,
C     31 DD5  , 32 DD6  , 33 PO1  , 34 PO2  , 35 PO3  , 36 PO4  ,
C     37 PO5  , 38 PO6  , 39 PO7  , 40 PO8  , 41 PO9  , 42 HYF  ,
C     43 HYFPD, 44 CORE , 45 EHEAT, 46 EISOL, 47 FN1  , 48 FN2  ,
C     49 FN3  , 50 ALPB , 51 BETPI, 52 BETSH, 53 BETPH, 54 ALPS ,
C     55 ALPP , 56 ALPPI, 57 ALPSH, 58 ALPPH, 59 FVAL1, 60 FVAL2,
C     61 GVAL1, 62 GVAL2, 63 ZSCOR, 64 FSCOR, 65 BCORE, 66 ACORE,
C     67 XSCAL, 68 XOFFL, 69 XOFFG, 70 ZSNMR, 71 ZPNMR, 72 ZDNMR,
C     73 BSNMR, 74 BPNMR, 75 BDNMR, 76 USNMR, 77 UPNMR, 78 UDNMR,
C     79 PDDGP, 80 PDDGD, 81 GSCAL.
      DATA PARTYP/'USS  ','UPP  ','ZS   ','ZP   ','BETAS','BETAP',
     1            'ALP  ','GSS  ','GPP  ','GSP  ','GP2  ','HSP  ',
     2            'UDD  ','ZD   ','BETAD','ZSN  ','ZPN  ','ZDN  ',
     3            'F0DD ','F2DD ','F4DD ','F0SD ','G2SD ','F0PD ',
     4            'F2PD ','G1PD ','G3PD ','DD2  ','DD3  ','DD4  ',
     5            'DD5  ','DD6  ','PO1  ','PO2  ','PO3  ','PO4  ',
     6            'PO5  ','PO6  ','PO7  ','PO8  ','PO9  ','HYF  ',
     7            'HYFPD','CORE ','EHEAT','EISOL','FN1  ','FN2  ',
     8            'FN3  ','ALPB ','BETPI','BETSH','BETPH','ALPS ',
     9            'ALPP ','ALPPI','ALPSH','ALPPH','FVAL1','FVAL2',
     A            'GVAL1','GVAL2','ZSCOR','FSCOR','BCORE','ACORE',
     B            'XSCAL','XOFFL','XOFFG','ZSNMR','ZPNMR','ZDNMR',
     C            'BSNMR','BPNMR','BDNMR','USNMR','UPNMR','UDNMR',
     D            'PDDGP','PDDGD','GSCAL'/
      DATA UNIT( 1)/'EV        ONE-CENTER ENERGY FOR S               '/
      DATA UNIT( 2)/'EV        ONE-CENTER ENERGY FOR P               '/
      DATA UNIT( 3)/'AU        ORBITAL EXPONENT  FOR S               '/
      DATA UNIT( 4)/'AU        ORBITAL EXPONENT  FOR P               '/
      DATA UNIT( 5)/'EV        BETA PARAMETER    FOR S               '/
      DATA UNIT( 6)/'EV        BETA PARAMETER    FOR P               '/
      DATA UNIT( 7)/'(1/A)     ALPHA PARAMETER   FOR CORE            '/
      DATA UNIT( 8)/'EV        ONE-CENTER INTEGRAL (SS,SS)           '/
      DATA UNIT( 9)/'EV        ONE-CENTER INTEGRAL (PP,PP)           '/
      DATA UNIT(10)/'EV        ONE-CENTER INTEGRAL (SS,PP)           '/
      DATA UNIT(11)/'EV        ONE-CENTER INTEGRAL (PP*,PP*)         '/
      DATA UNIT(12)/'EV        ONE-CENTER INTEGRAL (SP,SP)           '/
      DATA UNIT(13)/'EV        ONE-CENTER ENERGY FOR D               '/
      DATA UNIT(14)/'AU        ORBITAL EXPONENT  FOR D               '/
      DATA UNIT(15)/'EV        BETA PARAMETER    FOR D               '/
      DATA UNIT(16)/'AU        INTERNAL EXPONENT FOR S - (IJ,KL)     '/
      DATA UNIT(17)/'AU        INTERNAL EXPONENT FOR P - (IJ,KL)     '/
      DATA UNIT(18)/'AU        INTERNAL EXPONENT FOR D - (IJ,KL)     '/
      DATA UNIT(19)/'EV        SLATER-CONDON PARAMETER F0DD          '/
      DATA UNIT(20)/'EV        SLATER-CONDON PARAMETER F2DD          '/
      DATA UNIT(21)/'EV        SLATER-CONDON PARAMETER F4DD          '/
      DATA UNIT(22)/'EV        SLATER-CONDON PARAMETER F0SD          '/
      DATA UNIT(23)/'EV        SLATER-CONDON PARAMETER G2SD          '/
      DATA UNIT(24)/'EV        SLATER-CONDON PARAMETER F0PD          '/
      DATA UNIT(25)/'EV        SLATER-CONDON PARAMETER F2PD          '/
      DATA UNIT(26)/'EV        SLATER-CONDON PARAMETER G1PD          '/
      DATA UNIT(27)/'EV        SLATER-CONDON PARAMETER G3PD          '/
      DATA UNIT(28)/'BOHR      CHARGE SEPARATION, SP, L=1            '/
      DATA UNIT(29)/'BOHR      CHARGE SEPARATION, PP, L=2            '/
      DATA UNIT(30)/'BOHR      CHARGE SEPARATION, SD, L=2            '/
      DATA UNIT(31)/'BOHR      CHARGE SEPARATION, PD, L=1            '/
      DATA UNIT(32)/'BOHR      CHARGE SEPARATION, DD, L=2            '/
      DATA UNIT(33)/'BOHR      KLOPMAN-OHNO TERM, SS, L=0            '/
      DATA UNIT(34)/'BOHR      KLOPMAN-OHNO TERM, SP, L=1            '/
      DATA UNIT(35)/'BOHR      KLOPMAN-OHNO TERM, PP, L=2            '/
      DATA UNIT(36)/'BOHR      KLOPMAN-OHNO TERM, SD, L=2            '/
      DATA UNIT(37)/'BOHR      KLOPMAN-OHNO TERM, PD, L=1            '/
      DATA UNIT(38)/'BOHR      KLOPMAN-OHNO TERM, DD, L=2            '/
      DATA UNIT(39)/'BOHR      KLOPMAN-OHNO TERM, PP, L=0            '/
      DATA UNIT(40)/'BOHR      KLOPMAN-OHNO TERM, DD, L=0            '/
      DATA UNIT(41)/'BOHR      KLOPMAN-OHNO TERM, CORE               '/
      DATA UNIT(42)/'DEBYE     DIPOLE HYBRIDIZATION TERM, SP         '/
      DATA UNIT(43)/'DEBYE     DIPOLE HYBRIDIZATION TERM, PD         '/
      DATA UNIT(44)/'E         CORE CHARGE                           '/
      DATA UNIT(45)/'KCAL/MOL  HEAT OF FORMATION OF THE ATOM (EXP)   '/
      DATA UNIT(46)/'EV        TOTAL ENERGY OF THE ATOM (CALC)       '/
      DATA UNIT(47)/'NONE      CORE REPULSION GAUSSIAN, PREFACTOR    '/
      DATA UNIT(48)/'(1/A**2)  CORE REPULSION GAUSSIAN, EXPONENT     '/
      DATA UNIT(49)/'ANGSTROM  CORE REPULSION GAUSSIAN, WIDTH        '/
      DATA UNIT(50)/'(1/A)     ALPHA BOND PARAMETER WITH ELEMENT     '/
      DATA UNIT(51)/'EV        BETA PARAMETER    FOR PI              '/
      DATA UNIT(52)/'EV        BETA PARAMETER    FOR S IN X-H BOND   '/
      DATA UNIT(53)/'EV        BETA PARAMETER    FOR P IN X-H BOND   '/
      DATA UNIT(54)/'AU        ALPHA RESONANCE PARAMETER FOR S       '/
      DATA UNIT(55)/'AU        ALPHA RESONANCE PARAMETER FOR P       '/
      DATA UNIT(56)/'AU        ALPHA RESONANCE PARAMETER FOR PI      '/
      DATA UNIT(57)/'AU        ALPHA RESONANCE PARAMETER FOR S IN X-H'/
      DATA UNIT(58)/'AU        ALPHA RESONANCE PARAMETER FOR P IN X-H'/
      DATA UNIT(59)/'NONE      F1 FACTOR FOR ORTHOGONALIZATION TERMS '/
      DATA UNIT(60)/'NONE      F2 FACTOR FOR ORTHOGONALIZATION TERMS '/
      DATA UNIT(61)/'NONE      G1 FACTOR FOR ORTHOGONALIZATION TERMS '/
      DATA UNIT(62)/'NONE      G2 FACTOR FOR ORTHOGONALIZATION TERMS '/
      DATA UNIT(63)/'AU        ORBITAL EXPONENT    FOR 1S CORE       '/
      DATA UNIT(64)/'EV        ONE-ELECTRON ENERGY FOR 1S CORE       '/
      DATA UNIT(65)/'EV        BETA  RESONANCE PARAMETER FOR 1S CORE '/
      DATA UNIT(66)/'AU        ALPHA RESONANCE PARAMETER FOR 1S CORE '/
      DATA UNIT(67)/'NONE      SCALE FACTOR FOR NMR SHIELDINGS       '/
      DATA UNIT(68)/'PPM       OFFSET FOR NMR SHIFTS, LIQUID PHASE   '/
      DATA UNIT(69)/'PPM       OFFSET FOR NMR SHIFTS, GAS PHASE      '/
      DATA UNIT(70)/'AU        ORBITAL EXPONENT  FOR S IN NMR        '/
      DATA UNIT(71)/'AU        ORBITAL EXPONENT  FOR P IN NMR        '/
      DATA UNIT(72)/'AU        ORBITAL EXPONENT  FOR D IN NMR        '/
      DATA UNIT(73)/'EV        BETA PARAMETER    FOR S IN NMR        '/
      DATA UNIT(74)/'EV        BETA PARAMETER    FOR P IN NMR        '/
      DATA UNIT(75)/'EV        BETA PARAMETER    FOR D IN NMR        '/
      DATA UNIT(76)/'EV        ONE-CENTER ENERGY FOR S IN NMR        '/
      DATA UNIT(77)/'EV        ONE-CENTER ENERGY FOR P IN NMR        '/
      DATA UNIT(78)/'EV        ONE-CENTER ENERGY FOR D IN NMR        '/
      DATA UNIT(79)/'EV        CORE REPULSION PDDG TERM, PREFACTOR   '/
      DATA UNIT(80)/'ANGSTROM  CORE REPULSION PDDG TERM, DISTANCE    '/
      DATA UNIT(81)/'NONE      GAUSSIAN CORE-CORE TERM SCALE FACTOR  '/
      DATA UNIT3G  /'NONE      GTO SCALE FACTOR  FOR S               '/
      DATA UNIT4G  /'NONE      GTO SCALE FACTOR  FOR P               '/
C *** FILE NUMBERS.
      NB6    = NBF(6)
C *** PRINT THE STANDARD PARAMETERS.
      WRITE(NB6,510)
      IF(IOP.NE.-5.AND.IOP.NE.-6.AND.IOP.NE.-8.AND.IOP.NE.-9
     1            .AND.IOP.NE.-22.AND.IOP.NE.-23) THEN
         IF(LORBS(NI).EQ.1) THEN
            WRITE(NB6,510)(NI,PARTYP(I),USS(NI,I),UNIT(I),I=1,7,2)
            WRITE(NB6,510) NI,PARTYP(8),GSS(NI,1),UNIT(8)
            WRITE(NB6,510) NI,PARTYP(33),PO(1,NI),UNIT(33)
            WRITE(NB6,510) NI,PARTYP(41),PO(9,NI),UNIT(41)
            WRITE(NB6,510) NI,PARTYP(44),CORE(NI),UNIT(44)
            WRITE(NB6,510) NI,PARTYP(45),EHEAT(NI),UNIT(45)
            WRITE(NB6,510) NI,PARTYP(46),EISOL(NI),UNIT(46)
         ELSE IF(LORBS(NI).EQ.4) THEN
            WRITE(NB6,510)(NI,PARTYP(I),USS(NI,I),UNIT(I),I=1,7)
            WRITE(NB6,510)(NI,PARTYP(7+I),GSS(NI,I),UNIT(7+I),I=1,5)
            WRITE(NB6,510)(NI,PARTYP(26+I),DD(I,NI),UNIT(26+I),I=2,3)
            WRITE(NB6,510)(NI,PARTYP(32+I),PO(I,NI),UNIT(32+I),I=1,3)
            WRITE(NB6,510) NI,PARTYP(41),PO(9,NI),UNIT(41)
            WRITE(NB6,510) NI,PARTYP(42),HYF(NI),UNIT(42)
            WRITE(NB6,510) NI,PARTYP(44),CORE(NI),UNIT(44)
            WRITE(NB6,510) NI,PARTYP(45),EHEAT(NI),UNIT(45)
            WRITE(NB6,510) NI,PARTYP(46),EISOL(NI),UNIT(46)
         ELSE IF(LORBS(NI).EQ.9) THEN
            WRITE(NB6,510)(NI,PARTYP(I),USS(NI,I),UNIT(I),I=1,7)
            WRITE(NB6,510)(NI,PARTYP(7+I),GSS(NI,I),UNIT(7+I),I=1,5)
            WRITE(NB6,510)(NI,PARTYP(12+I),UDD(NI,I),UNIT(12+I),I=1,3)
            WRITE(NB6,510)(NI,PARTYP(15+I),ZSN(NI,I),UNIT(15+I),I=1,3)
            WRITE(NB6,510)(NI,PARTYP(18+I),F0DD(NI,I),UNIT(18+I),I=1,9)
            WRITE(NB6,510)(NI,PARTYP(26+I),DD(I,NI),UNIT(26+I),I=2,6)
            WRITE(NB6,510)(NI,PARTYP(32+I),PO(I,NI),UNIT(32+I),I=1,9)
            WRITE(NB6,510) NI,PARTYP(42),HYF(NI),UNIT(42)
            WRITE(NB6,510) NI,PARTYP(43),HYFPD(NI),UNIT(43)
            WRITE(NB6,510) NI,PARTYP(44),CORE(NI),UNIT(44)
            WRITE(NB6,510) NI,PARTYP(45),EHEAT(NI),UNIT(45)
            WRITE(NB6,510) NI,PARTYP(46),EISOL(NI),UNIT(46)
         ENDIF
      ENDIF
C *** PRINT PARAMETERS FOR GAUSSIANS IN AM1 AND PM3.
      IF(IOP.EQ.-2 .OR. IOP.EQ.-7 .OR. IOP.EQ.-12 .OR. IOP.EQ.-17) THEN
         IMPP   = IMP(NI)
         DO 10 I=1,IMPP
         WRITE(NB6,520) NI,PARTYP(47),GUESS1(NI,I),UNIT(47),I
         WRITE(NB6,520) NI,PARTYP(48),GUESS2(NI,I),UNIT(48),I
         WRITE(NB6,520) NI,PARTYP(49),GUESS3(NI,I),UNIT(49),I
   10    CONTINUE
         WRITE(NB6,510) NI,PARTYP(81),GSCAL(NI),UNIT(81)
      ENDIF
C *** PRINT PARAMETERS FOR PDDG TERMS IN MNDO AND PM3.
      IF((IOP.EQ.0 .OR. IOP.EQ.-4 .OR. IOP.EQ.-7).AND.IN2(11).EQ.8) THEN
         DO 20 I=1,2
         WRITE(NB6,520) NI,PARTYP(79),PA(NI,I),UNIT(79),I
         WRITE(NB6,520) NI,PARTYP(80),DA(NI,I),UNIT(80),I
   20    CONTINUE
      ENDIF
C *** PRINT BOND PARAMETERS IN MNDO/d.
      IF(IOP.EQ.-10 .OR. IOP.EQ.-12 .OR. IOP.EQ.-13) THEN
         MALPNI = MALPB(NI)
         IF(MALPNI.GT.0) THEN
            DO 30 I=1,MALPNI
            IF(ALPB(I,NI).GT.ZERO) THEN
               WRITE(NB6,520) NI,PARTYP(50),ALPB(I,NI),UNIT(50),I
            ENDIF
   30       CONTINUE
         ENDIF
      ENDIF
C *** PRINT NMR-SPECIFIC MNDO PARAMETERS.
C     THE CURRENT PARAMETRIZATIONS USE XBETAN=XBETAS AND XZETAN=XZETAS.
C     THEREFORE, XBETAN AND XZETAN ARE NOT PRINTED PRESENTLY.
      IF(IOP.EQ.0 .AND. NMR.GT.0 .AND. IDEFN(NI).GT.0) THEN
       IF(LORBS(NI).EQ.1) THEN
          LMAXP = 1
       ELSE IF(LORBS(NI).EQ.4) THEN
          LMAXP = 2
       ELSE IF(LORBS(NI).EQ.9) THEN
          LMAXP = 3
       ENDIF
       WRITE(NB6,510) NI,PARTYP(67),XSCALN(NI),UNIT(67)
       WRITE(NB6,510)(NI,PARTYP(67+I),XOFFN (NI,I),UNIT(67+I),I=1,2)
       WRITE(NB6,510)(NI,PARTYP(69+I),XZETAN(NI,I),UNIT(69+I),I=1,LMAXP)
       WRITE(NB6,510)(NI,PARTYP(72+I),XBETAN(NI,I),UNIT(72+I),I=1,LMAXP)
C      IF(IDEFN(I).GE.3) THEN
C         WRITE(NB6,510)(NI,PARTYP(75+I),XUS(NI,I),UNIT(75+I),I=1,LMAXP)
C      ENDIF
      ENDIF
C *** PRINT PARAMETERS FOR METHODS WITH ORTHOGONALIZATION CORRECTIONS.
      IF(IOP.EQ.-5 .OR. IOP.EQ.-6 .OR. IOP.EQ.-8 .OR. IOP.EQ.-9
     1             .OR. IOP.EQ.-22.OR. IOP.EQ.-23) THEN
        IF(LORBS(NI).EQ.1) THEN
          WRITE(NB6,510) NI,PARTYP(1),USS(NI,1),UNIT(1)
          WRITE(NB6,510) NI,PARTYP(3),USS(NI,3),UNIT3G
          WRITE(NB6,510) NI,PARTYP(5),USS(NI,5),UNIT(5)
          WRITE(NB6,510) NI,PARTYP(8),GSS(NI,1),UNIT(8)
          WRITE(NB6,510) NI,PARTYP(44),CORE(NI),UNIT(44)
          WRITE(NB6,510) NI,PARTYP(45),EHEAT(NI),UNIT(45)
          WRITE(NB6,510) NI,PARTYP(46),EISOL(NI),UNIT(46)
          WRITE(NB6,510) NI,PARTYP(54),OMM(NI,4),UNIT(54)
          WRITE(NB6,510) NI,PARTYP(52),OMM(NI,2),UNIT(52)
          WRITE(NB6,510) NI,PARTYP(57),OMM(NI,7),UNIT(57)
C         FVAL1 APPEARS IN ALL OMx AND ODMx METHODS.
          WRITE(NB6,510) NI,PARTYP(59),OMM(NI,9),UNIT(59)
C         FVAL2 APPEARS IN ALL METHODS EXCEPT OM3 AND ODM3.
          IF(IOP.NE.-8.AND.IOP.NE.-23) THEN
            WRITE(NB6,510) NI,PARTYP(60),OMM(NI,10),UNIT(60)
          ENDIF
C         GVAL1 APPEARS IN ALL METHODS EXCEPT OM1.
          IF(IOP.NE.-5) THEN
            WRITE(NB6,510) NI,PARTYP(61),OMM(NI,11),UNIT(61)
          ENDIF
C         GVAL2 APPEARS ONLY IN OM2, OM4, AND ODM2.
          IF(IOP.EQ.-6.OR.IOP.EQ.-9.OR.IOP.EQ.-22) THEN
            WRITE(NB6,510) NI,PARTYP(62),OMM(NI,12),UNIT(62)
          ENDIF
        ELSE IF(LORBS(NI).EQ.4) THEN
          WRITE(NB6,510)(NI,PARTYP(I),USS(NI,I),UNIT(I),I=1,2)
          WRITE(NB6,510) NI,PARTYP(3),USS(NI,3),UNIT3G
          WRITE(NB6,510) NI,PARTYP(4),USS(NI,4),UNIT4G
          WRITE(NB6,510)(NI,PARTYP(I),USS(NI,I),UNIT(I),I=5,6)
          WRITE(NB6,510)(NI,PARTYP(7+I),GSS(NI,I),UNIT(7+I),I=1,5)
          WRITE(NB6,510) NI,PARTYP(42),HYF(NI),UNIT(42)
          WRITE(NB6,510) NI,PARTYP(44),CORE(NI),UNIT(44)
          WRITE(NB6,510) NI,PARTYP(45),EHEAT(NI),UNIT(45)
          WRITE(NB6,510) NI,PARTYP(46),EISOL(NI),UNIT(46)
          WRITE(NB6,510)(NI,PARTYP(50+I),OMM(NI,I),UNIT(50+I),I=1,8)
C         FVAL1 APPEARS IN ALL OMx AND ODMx METHODS.
          WRITE(NB6,510) NI,PARTYP(59),OMM(NI,9),UNIT(59)
C         FVAL2 APPEARS IN ALL METHODS EXCEPT OM3 AND ODM3.
          IF(IOP.NE.-8.AND.IOP.NE.-23) THEN
            WRITE(NB6,510) NI,PARTYP(60),OMM(NI,10),UNIT(60)
          ENDIF
C         GVAL1 APPEARS IN ALL METHODS EXCEPT OM1.
          IF(IOP.NE.-5) THEN
            WRITE(NB6,510) NI,PARTYP(61),OMM(NI,11),UNIT(61)
          ENDIF
C         GVAL2 APPEARS ONLY IN OM2, OM4, AND ODM2.
          IF(IOP.EQ.-6.OR.IOP.EQ.-9.OR.IOP.EQ.-22) THEN
            WRITE(NB6,510) NI,PARTYP(62),OMM(NI,12),UNIT(62)
          ENDIF
C         A CORE-CORE REPULSION POTENTIAL APPEARS IN ALL METHODS EXCEPT OM1.
          IF(IOP.NE.-5) THEN
           WRITE(NB6,510)(NI,PARTYP(62+I),OMM(NI,12+I),UNIT(62+I),I=1,4)
          ENDIF
        ENDIF
      ENDIF
      RETURN
  510 FORMAT(   1X,I3,2X,A,F15.8,2X,A)
  520 FORMAT(   1X,I3,2X,A,F15.8,2X,A,I2)
      END
