      SUBROUTINE PQDEN (PA,PB,Q,LM4,LMQ)
C     *
C     COLLECT ONE-CENTER PAIR POPULATIONS AND CORE CHARGES.
C     *
      USE LIMIT, ONLY: LM1, LMI, LMZ
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./ATOMS / NUMAT,NAT(LM1),NFIRST(LM1),NLAST(LM1)
     ./FINDX1/ IP(LMI),IP1(LMI),IP2(LMI)
     ./PARDER/ TORE(LMZ),EHEAT(LMZ),EISOL(LMZ)
      DIMENSION PA(LM4),PB(LM4),Q(LMQ)
      LM6    = LMQ-NUMAT
      DO 10 J=1,LM6
      JM     = IP(J)
      Q(J)   =-PA(JM)-PB(JM)
      IF(IP1(J).NE.IP2(J)) Q(J)=Q(J)*2.0D0
   10 CONTINUE
      DO 20 J=1,NUMAT
      Q(LM6+J) = TORE(NAT(J))
   20 CONTINUE
      RETURN
      END
