      SUBROUTINE PRTCIS
C     *
C     PRINT RESULTS FOR MINIMAL CONFIGURATION INTERACTION.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*3 NTYPE(3,4)
      COMMON
     ./CCIS  / K,L,NCI,LROOT
     ./ENERGT/ EE,ENUCLR,EAT,ATHEAT
     ./INOPT2/ IN2(300)
     ./NBFILE/ NBF(20)
     ./ORBITS/ NUMB,NORBS,NMOS,NALPHA,NBETA
     ./XCI   / E(6),ENGYCI(3),VECTCI(3,3),ECI(3),BKCAL(3)
      DATA NTYPE/'KK ','LL ','KL ','KL ','KK ','LL ',
     1           ' K ',' L ','   ','KKL','KLL','   '/
C *** FILE NUMBERS.
      NB6    = NBF(6)
C *** INITIALIZATION.
      IMULT  = IN2(66)
      LINCI  = (NCI*(NCI+1))/2
      DO 10 IX=1,NCI
      KX     = (IX*(IX+1))/2
      E(KX)  = E(KX)+ENUCLR
      ENGYCI(IX) = ENGYCI(IX)+ENUCLR
   10 CONTINUE
C *** PRINT CONFIGURATIONS.
      WRITE(NB6,100)
      WRITE(NB6,110) K,L
      WRITE(NB6,120) (I,I=1,NCI)
      ICOL   = IMULT+1
      IF(ICOL.EQ.3 .AND. L.LE.NUMB) ICOL=4
      WRITE(NB6,130) (NTYPE(I,ICOL),I=1,NCI)
C *** PRINT ENERGIES OF CONFIGURATIONS.
      WRITE(NB6,150)
      WRITE(NB6,160) (I,I=1,NCI)
      WRITE(NB6,170) (BKCAL(I),I=1,NCI)
C *** PRINT CI MATRIX.
      WRITE(NB6,140)
      CALL VECPRT(E,LINCI,NCI)
C *** PRINT EIGENVALUES AND EIGENVECTORS.
      WRITE(NB6,180)
      CALL MATOUT(VECTCI,ENGYCI,NCI,NCI,NCI,NCI)
C *** PRINT ENERGIES OF CI STATES.
      WRITE(NB6,190)
      WRITE(NB6,160) (I,I=1,NCI)
      WRITE(NB6,170) (ECI(I),I=1,NCI)
      IF(LROOT.GT.1) WRITE(NB6,200) LROOT
      RETURN
  100 FORMAT(/// 1X,'SUMMARY OF CI-RESULTS')
  110 FORMAT(///1X,'ORBITALS INVOLVED IN CI  ',2I8,
     1       / 33X,'K',7X,'L')
  120 FORMAT(/  1X,'CONFIGURATION',10X,3(I2,6X))
  130 FORMAT(   1X,'OCCUPATION   ',10X,3(A3,5X))
  140 FORMAT(///1X,'CI MATRIX BEFORE DIAGONALIZATION (IN EV)'/)
  150 FORMAT(///1X,'HEATS OF FORMATION (IN KCAL/MOL) ',
     1             'FOR THE CONFIGURATIONS'/)
  160 FORMAT(  12X,10(I2,10X))
  170 FORMAT(   5X,10F12.5)
  180 FORMAT(///1X,'LOWEST EIGENVALUES (IN EV) AND EIGENVECTORS',
     1             ' OF THE CI MATRIX')
  190 FORMAT(///1X,'HEATS OF FORMATION (IN KCAL/MOL) ',
     1             'FOR THE CI STATES'/)
  200 FORMAT(///1X,'GEOMETRY OPTIMIZATION FOR CI STATE',I3)
      END
