      SUBROUTINE PRTEXC
C     *
C     PRINT ENERGIES OF SINGLY EXCITED CONFIGURATIONS.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./NBFILE/ NBF(20)
     ./PAR4  / EXCIT(20),NEXCIT,IEXCIT(4,20)
      IF(NEXCIT.EQ.0) RETURN
C *** FILE NUMBERS.
      NB6    = NBF(6)
C *** LOOP OVER SINGLY EXCITED CONFIGURATIONS.
      KK     = 0
      DO 10 J=1,NEXCIT
      IMULT  = IEXCIT(3,J)
      IF(IMULT.NE.1 .AND. IMULT.NE.3) GO TO 10
      II     = IEXCIT(1,J)
      IU     = IEXCIT(2,J)
      KK     = KK+1
      IF(KK.EQ.1) WRITE(NB6,100)
      WRITE(NB6,110) IMULT,II,IU,EXCIT(J)
   10 CONTINUE
      RETURN
  100 FORMAT (///1X,'ENERGY OF SINGLY EXCITED CONFIGURATIONS (EV)'//,
     1           1X,'IMULT',3X,'EXCITATION',3X,'CALCULATED'/)
  110 FORMAT (   1X,I5,3X,2I5,F13.5)
      END
