      SUBROUTINE PRTGPU
      USE LIMIT, ONLY: MAXGPU
      IMPLICIT NONE
      INTEGER NUMGPU, NVCAPA, MIBGLO, NBF, NB6, I
      CHARACTER*80 GPUNAM
      COMMON
     ./GPUPRP/ GPUNAM(MAXGPU),NVCAPA(MAXGPU),MIBGLO(MAXGPU),NUMGPU
     ./NBFILE/ NBF(20)
C *** FILE NUMBERS.
      NB6    = NBF(6)
C *** SILENTLY EXIT IF THIS DISTRIBUTION DOES NOT SUPPORT CUDA.
      IF(NUMGPU.LT.0) RETURN
C *** PRINT DEVICES.
      IF(NUMGPU.GT.0) THEN
         WRITE(NB6,510) NUMGPU
         WRITE(NB6,520)
         DO I=1,NUMGPU
            WRITE(NB6,530) I-1, NVCAPA(I)/10, MOD(NVCAPA(I),10),
     1                     MIBGLO(I), GPUNAM(I)
         END DO
         RETURN
      ENDIF
      WRITE(NB6,500)
      RETURN
  500 FORMAT(//1X,'NO CUDA-CAPABLE DEVICES DETECTED.')
  510 FORMAT(//1X,'NUMBER OF CUDA-CAPABLE DEVICES DETECTED:',I3)
  520 FORMAT(/ 1X,'  I   CAPA   MEM/MIB   DEVICE NAME')
  530 FORMAT(  1X,I3,I5,'.',I1,I9,4X,A)
      END
