C     ******************************************************************
      SUBROUTINE PRTNCG (NCG,MOL)
C     *
C     PRINT STATISTICS FOR RUNS WITH MORE THAN ONE MOLECULE.
C     ESPECIALLY FOR CONJUGATE GRADIENT DENSITY MATRIX SEARCHES.
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     NCG(20)   STATISTICAL DATA FROM COMPUTATIONAL ROUTINES (I).
C     MOL       NUMBER OF MOLECULES IN INPUT FILE (I).
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./INOPT2/ IN2(300)
     ./NBFILE/ NBF(20)
      DIMENSION NCG(20)
C *** COMMENT FOR NCG(20)
C     NCG(1) TO NCG(8) : USED FOR LINEAR SCALING CG-DMS APPROACH
C     NCG(9)  : TOTAL NUMBER OF SCF ITERATIONS
C     NCG(10) : NUMBER OF CONVERGED SCF TREATMENTS
C     NCG(11) : NUMBER OF UNSUCCESSFUL OPTIMIZATIONS
C     NCG(12) : NUMBER OF SCF CONVERGENCE PROBLEMS
C     NCG(13) : TOTAL NUMBER OF DIAGONALIZATIONS
C     NCG(14) : TOTAL NUMBER OF PSEUDODIAGONALIZATIONS
C     NCG(15) : NUMBER OF ERRORS IN INPUT FILE
C     NCG(16) TO NCG(20) : UNUSED
C *** FILE NUMBER.
      NB6 = NBF(6)
C *** INPUT OPTIONS.
      IOP    = IN2(2)
      JOP    = IN2(3)
      IDIIS  = IN2(9)
      ISCF   = IN2(35)
      IPLSCF = IN2(36)
      LINDMS = IN2(56)
      KTRIAL = IN2(67)
      IFAST  = IN2(73)
      NSTART = IN2(78)
      NSTEP  = IN2(79)
C *** PRINTING SECTION.
      IF(MOL.GT.1) THEN
         WRITE(NB6,500)
      ELSE
         WRITE(NB6,505)
      ENDIF
      IF(NCG(15).GT.0)WRITE(NB6,509) NCG(15)
      IF(LINDMS.GT.0) WRITE(NB6,510)
      WRITE(NB6,520) MOL,NCG(10),NCG(9)
      IF(LINDMS.GT.0) THEN
         WRITE(NB6,530) (NCG(I),I=1,8)
      ELSE
         WRITE(NB6,535) NCG(13),NCG(14),NCG(3)
      ENDIF
      IF(JOP.GE.0) WRITE(NB6,540) MOL-NCG(11)-NCG(12)-NCG(15),
     1             NCG(11),NCG(12)
      WRITE(NB6,550) IOP,JOP,LINDMS,IDIIS,ISCF,IPLSCF
      WRITE(NB6,560) KTRIAL,IFAST,NSTART,NSTEP
      CALL CPUSEC (TTOTAL)
      WRITE(NB6,570) TTOTAL
      RETURN
  500 FORMAT(///1X,'STATISTICS FOR RUNS WITH MANY MOLECULES')
  505 FORMAT(///1X,'STATISTICS FOR RUNNING A SINGLE MOLECULE')
  509 FORMAT(/  1X,'NUMBER OF ERRORS IN INPUT FILE        ',I10)
  510 FORMAT(   1X,'USING CONJUGATE GRADIENT DENSITY MATRIX SEARCHES')
  520 FORMAT(/  1X,'NUMBER OF MOLECULES FROM INPUT FILE   ',I10,
     1       /  1X,'NUMBER OF CONVERGED SCF TREATMENTS    ',I10,
     2       /  1X,'TOTAL NUMBER OF SCF ITERATIONS        ',I10)
  530 FORMAT(   1X,'TOTAL NUMBER OF CG  CYCLES            ',I10,
     1       /  1X,'TOTAL NUMBER OF PURIFICATIONS         ',I10,
     2       /  1X,'TOTAL NUMBER OF MATRIX MULTIPLICATIONS',I10,
     3       /  1X,'LINEAR ROOTS ACCEPTED                 ',I10,
     4       /  1X,'QUADRATIC ROOTS, BY PRESELECTION      ',I10,
     5       /  1X,'QUADRATIC ROOTS, BY COMPARISON        ',I10,
     6       /  1X,'CG SEARCHES CONVERGED                 ',I10,
     7       /  1X,'CG SEARCHES NOT CONVERGED             ',I10)
  535 FORMAT(   1X,'TOTAL NUMBER OF DIAGONALIZATIONS      ',I10,
     1       /  1X,'TOTAL NUMBER OF PSEUDODIAGONALIZATIONS',I10,
     2       /  1X,'TOTAL NUMBER OF MATRIX MULTIPLICATIONS',I10)
  540 FORMAT(/  1X,'GEOMETRY OPTIMIZATIONS                ',
     1       /  1X,'NUMBER OF SUCCESSFUL OPTIMIZATIONS    ',I10,
     2       /  1X,'NUMBER OF UNSUCCESSFUL OPTIMIZATIONS  ',I10,
     3       /  1X,'NUMBER OF SCF CONVERGENCE PROBLEMS    ',I10)
  550 FORMAT(/  1X,'RELEVANT GLOBAL INPUT OPTIONS         ',
     1       /  1X,'IOP    =',I5,5X,'JOP    =',I5,
     2       /  1X,'LINDMS =',I5,5X,'IDIIS  =',I5,
     3       /  1X,'ISCF   =',I5,5X,'IPLSCF =',I5)
  560 FORMAT(/  1X,'RELEVANT MOLECULE-SPECIFIC INPUT OPTIONS',
     1       /  1X,'KTRIAL =',I5,5X,'IFAST  =',I5,
     2       /  1X,'NSTART =',I5,5X,'NSTEP  =',I5)
  570 FORMAT(/  1X,'TOTAL COMPUTATION TIME',F18.3,' SECONDS')
      END
