      SUBROUTINE QMMOUT
C     *
C     PRINT PROPERTIES AT EXTERNAL POINTS.
C     *
      USE LIMIT, ONLY: LM1M
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./INOPT2/ IN2(300)
     ./NBFILE/ NBF(20)
     ./QMMM1 / COORDM(3,LM1M),CHARGM(LM1M)
     ./QMMM4 / ELPOT(LM1M),ESF(3,LM1M)
C *** INPUT OPTIONS.
      MMINP  = IN2(12)
      NPRINT = IN2(72)
      NUMATM = IN2(120)
      MMCOUP = IN2(121)
      MMPOT  = IN2(122)
      MMLINK = IN2(123)
      IF(MMINP.LE.0) RETURN
      IF(NUMATM.GT.100 .AND. NPRINT.LT.2) RETURN
C *** FILE NUMBERS.
      NB6    = NBF(6)
C *** PRINT OPTIONS, INPUT COORDINATES AND CHARGES.
      WRITE(NB6,500) MMCOUP,MMPOT,MMLINK
      WRITE(NB6,510)
      DO 10 I=1,NUMATM
      WRITE(NB6,520) I,(COORDM(J,I),J=1,3),CHARGM(I)
   10 CONTINUE
C *** PRINT ELECTROSTATIC POTENTIAL AND ELECTRIC FIELD.
      IF((MMCOUP.LT.3) .OR. (MMCOUP.EQ.4)) THEN
         WRITE(NB6,530)
         DO 20 I=1,NUMATM
         WRITE(NB6,520) I,ELPOT(I)
   20    CONTINUE
      ELSE
         WRITE(NB6,540)
         DO 30 I=1,NUMATM
         WRITE(NB6,520) I,ELPOT(I),(ESF(L,I),L=1,3)
   30    CONTINUE
      ENDIF
C *** SPECIFY TYPE OF COMPUTATION.
      WRITE(NB6,600)
      IF(MMPOT.EQ.1) THEN
         WRITE(NB6,610)
      ELSE IF(MMPOT.EQ.2) THEN
         WRITE(NB6,620)
      ELSE IF(MMPOT.EQ.3) THEN
         WRITE(NB6,630)
      ELSE IF(MMPOT.EQ.4) THEN
         WRITE(NB6,640)
      ELSE IF(MMPOT.EQ.5) THEN
         WRITE(NB6,650)
      ELSE IF(MMPOT.EQ.6) THEN
         WRITE(NB6,660)
      ELSE IF(MMPOT.EQ.7) THEN
         WRITE(NB6,670)
      ELSE IF(MMPOT.EQ.8) THEN
         WRITE(NB6,680)
      ENDIF
      IF(MMCOUP.EQ.3) WRITE(NB6,690)
      IF(MMLINK.EQ.1) WRITE(NB6,700)
      RETURN
  500 FORMAT(///1X,'PROPERTIES AT EXTERNAL POINTS EVALUATED WITH',
     1          1X,'THE OPTIONS:',
     2       /  1X,'MMCOUP =',I2,
     3       /  1X,'MMPOT  =',I2,
     4       /  1X,'MMLINK =',I2)
  510 FORMAT(///1X,'CARTESIAN COORDINATES (ANGSTROM) AND CHARGES (E)',
     1          1X,'OF THE EXTERNAL POINTS.',
     2       // 5X,'I',10X,'X',11X,'Y',11X,'Z',9X,'CHARGE'/)
  520 FORMAT(1X,I5,2X,4F12.5)
  530 FORMAT(///1X,'ELECTROSTATIC POTENTIAL (VOLT).',
     1       // 5X,'I',9X,'ELPOT'/)
  540 FORMAT(///1X,'ELECTROSTATIC POTENTIAL (VOLT) AND ELECTRIC FIELD',
     1          1X,'COMPONENTS (KCAL/(MOL*ANGSTROM*E)).',
     2       // 5X,'I',9X,'ELPOT',6X,'FIELDX',6X,'FIELDY',6X,'FIELDZ'/)
  600 FORMAT(///1X,'COMPUTATIONAL APPROACH TO ELECTROSTATIC POTENTIAL:')
  610 FORMAT(   1X,'CLASSICAL EVALUATION USING MONOPOLES ONLY.')
  620 FORMAT(   1X,'CLASSICAL EVALUATION USING MONOPOLES, DIPOLES,',
     1          1X,'AND QUADRUPOLES.')
  630 FORMAT(   1X,'SEMIEMPIRICAL EVALUATION USING A CLASSICAL UNIT',
     1          1X,'TEST CHARGE AND STANDARD PARAMETERS.')
  640 FORMAT(   1X,'SEMIEMPIRICAL EVALUATION USING A CLASSICAL UNIT',
     1          1X,'TEST CHARGE AND A ONE-PARAMETRIC INTERACTION',
     2          1X,'FUNCTION (BAKOWIES-THIEL 1996).')
  650 FORMAT(   1X,'SEMIEMPIRICAL EVALUATION USING A CLASSICAL UNIT',
     1          1X,'TEST CHARGE AND A TWO-PARAMETRIC INTERACTION',
     2          1X,'FUNCTION (BAKOWIES-THIEL 1996).')
  660 FORMAT(   1X,'SEMIEMPIRICAL EVALUATION USING A CLASSICAL UNIT',
     1          1X,'TEST CHARGE AND A TWO-PARAMETRIC INTERACTION',
     2          1X,'FUNCTION (FORD-WANG 1993).')
  670 FORMAT(   1X,'SEMIEMPIRICAL EVALUATION AS SPECIFIED BY',
     1          1X,'FIELD-BASH-KARPLUS (1990).')
  680 FORMAT(   1X,'SEMIEMPIRICAL EVALUATION REPRESENTING THE TEST',
     1          1X,'CHARGE BY HYDROGEN AND USING STANDARD PARAMETERS',
     2          1X,'(CUMMINS-GREADY 1990).')
  690 FORMAT(   1X,'ELECTRIC FIELD DETERMINED AS NEGATIVE GRADIENT',
     1          1X,'OF THE ELECTROSTATIC POTENTIAL.')
  700 FORMAT(   1X,'CONTRIBUTIONS FROM LINK ATOMS NOT INCLUDED.')
      END
