      SUBROUTINE RIJCHK (COORD,NN,NATOMS,KSTOP)
C     *
C     CHECK FOR ZERO INTERATOMIC DISTANCES.
C     *
C     NOTATION. I=INPUT, O=OUTPUT.
C     COORD     CARTESIAN COORDINATES (I).
C     NN        ATOMIC NUMBERS (I).
C     NATOMS    NUMBER OF ATOMS (I).
C     KSTOP     NUMBER OF ATOM PAIRS WITH ZERO DISTANCE (O).
C               DUMMY ATOMS ARE IGNORED IN THIS COUNT.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (SMALL=1.0D-12)
      DIMENSION COORD(3,NATOMS),NN(NATOMS)
      KSTOP  = 0
      DO 20 I=2,NATOMS
      IF(NN(I).NE.99) THEN
         DO 10 J=1,I-1
         IF(NN(J).NE.99) THEN
            RIJ2 = (COORD(1,I)-COORD(1,J))**2
     1            +(COORD(2,I)-COORD(2,J))**2
     2            +(COORD(3,I)-COORD(3,J))**2
            IF(RIJ2.LT.SMALL) KSTOP=KSTOP+1
         ENDIF
   10    CONTINUE
      ENDIF
   20 CONTINUE
      RETURN
      END
