      SUBROUTINE SCFFRG (A,LM5,NITER,LM2,LM4,LM6,LM9,
     1                   LS1,LS2,LS3,LS5,LS6,LS7,LS8,LS9,
     2                   LG1,LG2,LG3,LG4)
C     *
C     FRAGMENT RHF-SCF CALCULATION TO GENERATE INITIAL DENSITY.
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     A(LM5)    AVAILABLE BUFFER (S).
C     NITER     NUMBER OF SCF ITERATIONS DONE (O).
C     LM*       DIMENSIONS OF SCF ARRAYS (I).
C     LS*       ADDRESSES FOR SCF ARRAYS (I).
C     LG*       ADDRESSES FOR OM2 ARRAYS (I).
C     *
C     USE LIMIT, ONLY: LM1
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./INOPT2/ IN2(300)
     ./NBFILE/ NBF(20)
     ./ORBITS/ NUMB,NORBS,NMOS,NALPHA,NBETA
      DIMENSION A(LM5)
C *** INPUT OPTIONS.
      IOP    = IN2(2)
      JPRINT = IN2(42)
C *** INTEGRAL CALCULATION FOR SCF.
      IF(IOP.GT.0) THEN
         CALL MINDO  (A(LS7),A(LS9),LM4,LM9)
      ELSE
         CALL HCOREP (A(LS7),A(LS9),A(LG1),A(LG2),A(LG3),A(LG4),
     1                LM2,LM4,LM6,LM9)
      ENDIF
C *** SCF PROCEDURE.
      CALL ITFRG (A(LS1),A(LS5),A(LS2),A(LS6),A(LS7),A(LS8),A(LS3),
     1            A(LS9),LM2,LM4,LM6,LM9,NITER)
C *** DEBUG PRINT OF CURRENT DENSITY MATRIX.
      IF(JPRINT.GE.5) THEN
         NB6 = NBF(6)
         WRITE(NB6,500)
         CALL VECPRT(A(LS8),LM4,NORBS)
      ENDIF
      RETURN
  500 FORMAT(///1X,'DENSITY MATRIX OF CURRENT FRAGMENT'/)
      END
