      SUBROUTINE SQUARE(A,B,N,LM2,LM4)
C     *
C     STORE LOWER TRIANGLE MATRIX A(LM4) AS SYMMETRIC SQUARE MATRIX
C     B(LM2,LM2). A AND B MAY OCCUPY THE SAME CORE SPACE.
C     N ROWS AND COLUMNS ARE COPIED.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(LM4),B(LM2,LM2)
      ID     = LM4
      DO 20 J=N,1,-1
      DO 10 I=J,1,-1
      B(I,J) = A(ID)
      ID     = ID-1
   10 CONTINUE
   20 CONTINUE
CFPP$ CONCUR
C$OMP PARALLEL DO SCHEDULE(DYNAMIC)
      DO 40 J=2,N
CDIR$ IVDEP
C$DIR NO_RECURRENCE
*VDIR NODEP
*VOCL LOOP,NOVREC
      DO 30 I=1,J-1
      B(J,I) = B(I,J)
   30 CONTINUE
   40 CONTINUE
C$OMP END PARALLEL DO
      RETURN
      END
