      SUBROUTINE TRPDIF (A,B,N,LM2,LM4)
C     *
C     DIFFERENCE OF A MATRIX AND ITS TRANSPOSE: B = A - A(TRANSPOSE).
C     B IS ANTISYMMETRIC: B(I,J) = - B(J,I).
C     THEREFORE ONLY A TRIANGULAR PART OF B NEEDS TO BE STORED.
C     B(LM4) CORRESPONDS TO THE LOWER TRIANGLE IN ROW-WISE ORDER.
C     A AND B MUST NOT OCCUPY THE SAME CORE SPACE.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(LM2,LM2),B(LM4)
      IJ     = 0
      DO 20 I=1,N
      DO 10 J=1,I
      IJ     = IJ+1
      B(IJ)  = A(I,J)-A(J,I)
   10 CONTINUE
   20 CONTINUE
      RETURN
      END
