      SUBROUTINE VERTEX (C,E,Q,W,LM2,LM3,LM6,LM9)
C     *
C     ENERGIES OF SINGLY EXCITED CONFIGURATIONS.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON
     ./INOPT2/ IN2(300)
     ./PAR4  / EXCIT(20),NEXCIT,IEXCIT(4,20)
C    ./NBFILE/ NBF(20)
      DIMENSION C(LM2,LM3),E(LM3),Q(LM6),W(LM9)
      IF(NEXCIT.LE.0) RETURN
C *** FILE NUMBERS.
C     NB6    = NBF(6)
C *** INPUT OPTIONS.
C     NPRINT = IN2(72)
      IMODE  = IN2(211)
C *** LOOP OVER EXCITATIONS.
      DO 10 J=1,NEXCIT
      II     = IEXCIT(1,J)
      IU     = IEXCIT(2,J)
      ITYPE  = IEXCIT(3,J)
C     VERTICAL EXCITATION ENERGY OF SINGLET (II-IU).
      IF(ITYPE.EQ.1) THEN
         IF(IMODE.GT.0) THEN
            XI  = SPCG(C(1,II),C(1,II),C(1,IU),C(1,IU),W,LM2,LM9)
            XJ  = SPCG(C(1,II),C(1,IU),C(1,II),C(1,IU),W,LM2,LM9)
         ELSE
            CALL WSTORE (W,LM6,-1)
            XI  = SPCW(C(1,II),C(1,II),C(1,IU),C(1,IU),Q,W,LM2,LM6)
            XJ  = SPCW(C(1,II),C(1,IU),C(1,II),C(1,IU),Q,W,LM2,LM6)
         ENDIF
         EXCIT(J) = E(IU)-E(II)-XI+2.D0*XJ
C        IF(NPRINT.GT.5) WRITE(NB6,100) II,IU,EXCIT(J),E(II),E(IU),XI,XJ
C     VERTICAL EXCITATION ENERGY OF TRIPLET (II-IU).
      ELSE IF(ITYPE.EQ.3) THEN
         IF(IMODE.GT.0) THEN
            XI  = SPCG(C(1,II),C(1,II),C(1,IU),C(1,IU),W,LM2,LM9)
         ELSE
            CALL WSTORE (W,LM6,-1)
            XI  = SPCW(C(1,II),C(1,II),C(1,IU),C(1,IU),Q,W,LM2,LM6)
         ENDIF
         EXCIT(J) = E(IU)-E(II)-XI
C        IF(NPRINT.GT.5) WRITE(NB6,100) II,IU,EXCIT(J),E(II),E(IU),XI
C     OTHER CASES NOT IMPLEMENTED.
      ELSE
         EXCIT(J) = 0.D0
      ENDIF
   10 CONTINUE
      RETURN
C 100 FORMAT (/1X,'VERTEX',2I5,10F10.5)
      END
