      SUBROUTINE W2LIN (ISTEP,KR,WW,W,LM9)
C     *
C     STORE TWO-CENTER TWO-ELECTRON INTEGRALS IN A LINEAR ARRAY.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION WW(2025),W(LM9)
      DO 10 I=1,ISTEP
      W(I+KR)=WW(I)
   10 CONTINUE
      KR     = KR+ISTEP
      RETURN
      END
