      SUBROUTINE W2MAT (IP,JP,WW,W,LM6,LIMIJ,LIMKL)
C     *
C     STORE TWO-CENTER TWO-ELECTRON INTEGRALS IN A SQUARE MATRIX.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION W(LM6,LM6),WW(LIMKL,LIMIJ)
      IPA    = IP-1
      JPA    = JP-1
      DO 20 KL=1,LIMKL
      DO 10 IJ=1,LIMIJ
      W(IPA+IJ,JPA+KL) = WW(KL,IJ)
   10 CONTINUE
   20 CONTINUE
      RETURN
      END
