      SUBROUTINE WINT (I,J,K,L,W,C,CC,C12,WW,LM2,LM3,LM7,NB3,KMAX)
C     *
C     CALCULATION OF A SINGLE TWO-ELECTRON MO INTEGRAL (IJ,KL).
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION C(LM2,LM3),CC(LM7),C12(KMAX),WW(KMAX)
      LMAX   = LM7/KMAX
      CALL CCPROD (C(1,I),C(1,J),C12,LM2,KMAX)
      CALL WWSTEP (C12,CC,WW,LM7,NB3,KMAX,LMAX)
      CALL CCPROD (C(1,K),C(1,L),C12,LM2,KMAX)
      W      = DDOT (KMAX,C12,1,WW,1)
      RETURN
      END
