      SUBROUTINE ZZERO (NR,NC,A,LM2)
C     *
C     INITIALIZATION OF THE MATRIX A(LM2,NC).
C     ROWS 1..NR AND COLUMNS 1..NC ARE SET TO ZERO.
C     *
C     THIS ROUTINE IS CALLED BEFORE PERFORMING MATRIX MULTIPLICATIONS
C     USING DGEMM (BLAS3) WHERE THE ARGUMENT BETA IS ZERO.
C     SCHEMATICALLY: C = ALPHA * A * B + BETA * C
C     MOST LIBRARY ROUTINES HANDLE THIS CASE WITHOUT ERRORS, EVEN IF
C     MATRIX C (MULTIPLIED BY BETA) IS INFINITE OR UNDEFINED.
C     THE IBM BLAS LIBRARY (AIX) FAILS UNDER THESE CIRCUMSTANCES
C     SO THAT MATRIX C NEEDS TO BE INITIALIZED TO ZERO.
C     *
C     TECHNICAL IMPLEMENTATION.
C     A DUMMY SUBROUTINE IS PROVIDED, WITH CODE ON COMMENT LINES.
C     THE IBM-SPECIFIC MAKEFILE WILL ACTIVATE THE CODE.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
CZR   PARAMETER (ZERO=0.D0)
      DIMENSION A(LM2,NC)
CZR   DO 20 J=1,NC
CZR   DO 10 I=1,NR
CZR   A(I,J) = ZERO
CZR10 CONTINUE
CZR20 CONTINUE
      RETURN
      END
