C     ******************************************************************
      SUBROUTINE MATUPM (A,B,FACTOR,LM2,N,UPMIN,UPMAX)
C     *
C     PERFORM MATRIX UPDATE: A + FACTOR*B, FOR DIAGONAL ELEMENTS ONLY,
C     AND RETURN MINIMUM AND MAXIMUM DIAGONAL ELEMENTS.
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     A(LM2,*)  FIRST  INPUT MATRIX (I).
C     B(LM2,*)  SECOND INPUT MATRIX (I).
C     FACTOR    UPDATE FACTOR (I).
C     LM2       LEADING DIMENSION (I).
C     N         NUMBER OF ORBITALS (I).
C     UPMIN     MINIMUM DIAGONAL ELEMENT AFTER UPDATE (O).
C     UPMAX     MAXIMUM DIAGONAL ELEMENT AFTER UPDATE (O).
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(LM2,N),B(LM2,N)
C *** INITIALIZATION FOR DENSITY MATRIX UPDATE.
      UPMIN  = 2.0D0
      UPMAX  = 0.0D0
C *** LOOP OVER DIAGONAL ELEMENTS.
      DO 10 I=1,N
      CII    = A(I,I) + FACTOR*B(I,I)
      UPMIN  = MIN(UPMIN,CII)
      UPMAX  = MAX(UPMAX,CII)
   10 CONTINUE
      RETURN
      END
