C     ******************************************************************
      SUBROUTINE PURIFY (P,Q,R,LM2,N)
C     *
C     McWEENY PURIFICATION TRANSFORMATION: R = 3 PP - 2 PPP.
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     P(LM2,*)  INPUT DENSITY MATRIX (I).
C     Q(LM2,*)  INTERMEDIATE MATRIX PRODUCT PP (S).
C     R(LM2,*)  PURIFIED DENSITY MATRIX (O).
C     LM2       LEADING DIMENSION (I).
C     N         NUMBER OF ORBITALS (I).
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (ZERO=0.0D0)
      PARAMETER (ONE=1.0D0)
      PARAMETER (TWO=2.0D0)
      PARAMETER (THREE=3.0D0)
      DIMENSION P(LM2,N),Q(LM2,N),R(LM2,N)
      CALL DGEMM ('N','N',LM2,N,N,ONE,P,LM2,P,LM2,ZERO,Q,LM2)
      CALL MATSCL (Q,R,THREE,LM2,N)
      CALL DGEMM ('N','N',LM2,N,N,-TWO,P,LM2,Q,LM2,ONE,R,LM2)
      RETURN
      END
