C     ******************************************************************
      SUBROUTINE TRMSUM (A,B,LM2,N)
C     *
C     SUM OF A SQUARE MATRIX AND ITS TRANSPOSE: B = A + A(TRANSPOSE).
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     A(LM2,*)  INPUT MATRIX (I).
C     B(LM2,*)  OUTPUT MATRIX (O).
C     LM2       LEADING DIMENSION (I).
C     N         NUMBER OF ORBITALS (I).
C     *
C     THE RESULTING MATRIX B IS SYMMETRIC. THE FULL SQUARE MATRIX IS
C     GENERATED ALTHOUGH THE LOWER OR UPPER TRIANGLE WOULD SUFFICE.
C     IN THE CODE BELOW, A AND B MUST NOT OCCUPY THE SAME CORE SPACE.
C     THIS COULD EASILY BE CHANGED, OF COURSE.
C     *
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(LM2,N),B(LM2,N)
      DO 20 J=1,N
      DO 10 I=1,N
      B(I,J) = A(I,J)+A(J,I)
   10 CONTINUE
   20 CONTINUE
      RETURN
      END
