C     ******************************************************************
      SUBROUTINE PSILSS(R,ARO,BRO,IMOD,W,W1,W2)
C
C  This subroutine is not intended to be human-readable.
C  It was generated by a Mathematica program (makeints.m).
C  General version of 14 May 1997.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION ARO(9), BRO(9)
      DIMENSION W(461),W1(461),W2(461)
      PARAMETER (CN1=3.D0)
      T1 = R**2
      T2 = SQRT(T1 + (ARO(1) + BRO(1))**2)
      W(1) = 1/T2
      T4 = SQRT(T1 + (ARO(2) + BRO(1))**2)
      W(2) = 1/T4
      T3 = SQRT(T1 + (ARO(1) + BRO(2))**2)
      W(16) = 1/T3
      T5 = SQRT(T1 + (ARO(2) + BRO(2))**2)
      W(17) = 1/T5
      IF( IMOD.LE.0 ) RETURN
C
C   Expressions for first derivatives
C
      T6 = T2**2
      T7 = T2*T6
      T8 = 1/T7
      W1(1) = -(R*T8)
      T12 = T4**2
      T13 = T12*T4
      T14 = 1/T13
      W1(2) = -(R*T14)
      T9 = T3**2
      T10 = T3*T9
      T11 = 1/T10
      W1(16) = -(R*T11)
      T15 = T5**2
      T16 = T15*T5
      T17 = 1/T16
      W1(17) = -(R*T17)
      IF( IMOD.LE.1 ) RETURN
C
C   Expressions for second derivatives
C
      W2(1) = CN1*T1/(T6*T7) - T8
      W2(2) = CN1*T1/(T12*T13) - T14
      W2(16) = -T11 + CN1*T1/(T10*T9)
      W2(17) = CN1*T1/(T15*T16) - T17
      RETURN
      END
