C     ******************************************************************
      SUBROUTINE PSILSX(R,ARO,IMOD,W,W1,W2)
C
C  This subroutine is not intended to be human-readable.
C  It was generated by a Mathematica program (makeints.m).
C  General version of 14 May 1997.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION ARO(9)
      DIMENSION W(461),W1(461),W2(461)
      PARAMETER (CN1=4.D0)
      PARAMETER (CN2=2.D0)
      PARAMETER (CN3=-4.D0)
      PARAMETER (CN4=3.D0)
      T1 = R**2
      T7 = ARO(1)**2
      T3 = SQRT(T1 + CN1*T7)
      W(1) = 1/T3
      T4 = SQRT(T1 + (ARO(1) + ARO(2))**2)
      T2 = 1/T4
      W(2) = T2
      W(16) = T2
      T15 = ARO(2)**2
      T6 = SQRT(T1 + CN1*T15)
      W(17) = 1/T6
      IF( IMOD.LE.0 ) RETURN
C
C   Expressions for first derivatives
C
      T8 = T3**2
      T9 = T3*T8
      W1(1) = -(R/T9)
      T10 = T4**2
      T11 = T10*T4
      T12 = 1/T11
      T5 = -(R*T12)
      W1(2) = T5
      W1(16) = T5
      T16 = T6**2
      T17 = T16*T6
      W1(17) = -(R/T17)
      IF( IMOD.LE.1 ) RETURN
C
C   Expressions for second derivatives
C
      T14 = CN2*T1
      W2(1) = (T14 + CN3*T7)/(T8*T9)
      T13 = CN4*T1/(T10*T11) - T12
      W2(2) = T13
      W2(16) = T13
      W2(17) = (T14 + CN3*T15)/(T16*T17)
      RETURN
      END
