C     ******************************************************************
      SUBROUTINE PSILPS(R,ARO,BRO,AD,IMOD,W,W1,W2)
C
C  This subroutine is not intended to be human-readable.
C  It was generated by a Mathematica program (makeints.m).
C  General version of 14 May 1997.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION ARO(9), BRO(9), AD(5)
      DIMENSION W(461),W1(461),W2(461)
      PARAMETER (CN1=-0.5D0)
      PARAMETER (CN2=0.5D0)
      PARAMETER (CN3=2.D0)
      PARAMETER (CN4=0.25D0)
      PARAMETER (CN5=1.4142135623730950488016887242096980785697D0)
      PARAMETER (CN6=-1.4142135623730950488016887242096980785697D0)
      PARAMETER (CN7=3.D0)
      PARAMETER (CN8=-1.5D0)
      PARAMETER (CN9=1.5D0)
      PARAMETER (CN10=0.75D0)
      PARAMETER (CN11=-0.25D0)
      T1 = R**2
      T18 = SQRT(T1 + (ARO(1) + BRO(1))**2)
      W(1) = 1/T18
      T20 = SQRT(T1 + (ARO(2) + BRO(1))**2)
      W(2) = 1/T20
      T3 = (ARO(3) + BRO(1))**2
      T2 = -R
      T22 = T2 - AD(1)
      T4 = T22**2
      T23 = SQRT(T3 + T4)
      T24 = T2 + AD(1)
      T5 = T24**2
      T25 = SQRT(T3 + T5)
      W(3) = CN1/T23 + CN2/T25
      T28 = SQRT(T1 + (ARO(5) + BRO(1))**2)
      T12 = 1/T28
      T7 = (ARO(4) + BRO(1))**2
      T30 = SQRT(T1 + T7)
      T13 = CN1/T30
      T8 = CN3*AD(2)**2
      T29 = SQRT(T1 + T7 + T8)
      T10 = T12 + T13 + CN2/T29
      W(4) = T10
      W(5) = T10
      T37 = T2 + CN5*AD(2)
      T15 = T37**2
      T38 = SQRT(T15 + T7)
      T39 = T2 + CN6*AD(2)
      T17 = T39**2
      T40 = SQRT(T17 + T7)
      W(6) = T12 + T13 + CN4/T38 + CN4/T40
      T19 = SQRT(T1 + (ARO(1) + BRO(2))**2)
      W(16) = 1/T19
      T21 = SQRT(T1 + (ARO(2) + BRO(2))**2)
      W(17) = 1/T21
      T6 = (ARO(3) + BRO(2))**2
      T26 = SQRT(T4 + T6)
      T27 = SQRT(T5 + T6)
      W(18) = CN1/T26 + CN2/T27
      T31 = SQRT(T1 + (ARO(5) + BRO(2))**2)
      T14 = 1/T31
      T9 = (ARO(4) + BRO(2))**2
      T33 = SQRT(T1 + T9)
      T16 = CN1/T33
      T32 = SQRT(T1 + T8 + T9)
      T11 = T14 + T16 + CN2/T32
      W(19) = T11
      W(20) = T11
      T43 = SQRT(T15 + T9)
      T44 = SQRT(T17 + T9)
      W(21) = T14 + T16 + CN4/T43 + CN4/T44
      IF( IMOD.LE.0 ) RETURN
C
C   Expressions for first derivatives
C
      T46 = T18**2
      T47 = T18*T46
      T48 = 1/T47
      W1(1) = -(R*T48)
      T52 = T20**2
      T53 = T20*T52
      T54 = 1/T53
      W1(2) = -(R*T54)
      T58 = T23**2
      T59 = T23*T58
      T60 = 1/T59
      T61 = T25**2
      T62 = T25*T61
      T63 = 1/T62
      W1(3) = CN1*T22*T60 + CN2*T24*T63
      T75 = T28**2
      T76 = T28*T75
      T77 = 1/T76
      T36 = -(R*T77)
      T70 = T30**2
      T71 = T30*T70
      T74 = 1/T71
      T41 = CN2*R*T74
      T72 = T29**2
      T73 = T29*T72
      T78 = 1/T73
      T34 = T36 + T41 + CN1*R*T78
      W1(4) = T34
      W1(5) = T34
      T92 = T40**2
      T93 = T40*T92
      T94 = 1/T93
      T96 = T38**2
      T97 = T38*T96
      T98 = 1/T97
      W1(6) = T36 + T41 + CN4*T39*T94 + CN4*T37*T98
      T49 = T19**2
      T50 = T19*T49
      T51 = 1/T50
      W1(16) = -(R*T51)
      T55 = T21**2
      T56 = T21*T55
      T57 = 1/T56
      W1(17) = -(R*T57)
      T64 = T26**2
      T65 = T26*T64
      T66 = 1/T65
      T67 = T27**2
      T68 = T27*T67
      T69 = 1/T68
      W1(18) = CN1*T22*T66 + CN2*T24*T69
      T84 = T31**2
      T85 = T31*T84
      T86 = 1/T85
      T42 = -(R*T86)
      T79 = T33**2
      T80 = T33*T79
      T83 = 1/T80
      T45 = CN2*R*T83
      T81 = T32**2
      T82 = T32*T81
      T87 = 1/T82
      T35 = T42 + T45 + CN1*R*T87
      W1(19) = T35
      W1(20) = T35
      T105 = T43**2
      T106 = T105*T43
      T107 = 1/T106
      T101 = T44**2
      T102 = T101*T44
      T103 = 1/T102
      W1(21) = CN4*T107*T37 + CN4*T103*T39 + T42 + T45
      IF( IMOD.LE.1 ) RETURN
C
C   Expressions for second derivatives
C
      W2(1) = CN7*T1/(T46*T47) - T48
      W2(2) = CN7*T1/(T52*T53) - T54
      W2(3) = CN8*T4/(T58*T59) + CN2*T60 + CN9*T5/(T61*T62) + CN1*T63
      T90 = CN8*T1/(T70*T71)
      T91 = CN2*T74
      T95 = CN7*T1/(T75*T76) - T77
      T88 = CN9*T1/(T72*T73) + CN1*T78 + T90 + T91 + T95
      W2(4) = T88
      W2(5) = T88
      W2(6) = T90 + T91 + CN10*T17/(T92*T93) + CN11*T94 + T95 + 
     1 CN10*T15/(T96*T97) + CN11*T98
      W2(16) = CN7*T1/(T49*T50) - T51
      W2(17) = CN7*T1/(T55*T56) - T57
      W2(18) = CN8*T4/(T64*T65) + CN2*T66 + CN9*T5/(T67*T68) + CN1*T69
      T100 = CN2*T83
      T104 = CN7*T1/(T84*T85) - T86
      T99 = CN8*T1/(T79*T80)
      T89 = T100 + T104 + CN9*T1/(T81*T82) + CN1*T87 + T99
      W2(19) = T89
      W2(20) = T89
      W2(21) = T100 + CN11*T103 + T104 + CN11*T107 + 
     1 CN10*T15/(T105*T106) + CN10*T17/(T101*T102) + T99
      RETURN
      END
