      SUBROUTINE INES
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'INES'
      RETURN
  600 FORMAT(//1X,'EXCITED-STATE MODULE NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE ESMAIN
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'ESMAIN'
      RETURN
  600 FORMAT(//1X,'EXCITED-STATE MODULE NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END
