      SUBROUTINE GUGACI
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'GUGACI'
      RETURN
  600 FORMAT(//1X,'CONFIGURATION INTERACTION NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END
