      SUBROUTINE PSDRV
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'PSDRV'
      RETURN
  600 FORMAT(//1X,'ANALYTIC DERIVATIVES NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END


      SUBROUTINE PSOMX
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'PSOMX'
      RETURN
  600 FORMAT(//1X,'SEMI-ANALYTIC DERIVATIVES NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END


      SUBROUTINE PSGSBP
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'PSGSBP'
      RETURN
  600 FORMAT(//1X,'ANALYTIC DERIVATIVES NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END


      SUBROUTINE PSNMR
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'PSNMR'
      RETURN
  600 FORMAT(//1X,'NMR CHEMICAL SHIFTS NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END


      LOGICAL FUNCTION LHAVPS()
      LHAVPS = .FALSE.
      RETURN
      END
