      SUBROUTINE INISD
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'INISD'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE INITSC
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'INITSC'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE SCOSMOADDFCK
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'SCOSMOADDFCK'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE SCOSMODIELECAV
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'SCOSMODIELECAV'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE SCOSMODGRAD
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'SCOSMODGRAD'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE SCOSMOPRTCSM
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'SCOSMOPRTCSM'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE CPEFCN
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'CPEFCN'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE PQDISP
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'PQDISP'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE SDISP
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'SDISP'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END



      SUBROUTINE SDGRAD
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'SDGRAD'
      RETURN
  600 FORMAT(//1X,'SMOOTH COSMO SOLVATION MODEL NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END
