      SUBROUTINE SCFDMS
      COMMON
     ./NBFILE/ NBF(20)
      NB6 = NBF(6)
      WRITE(NB6,600)
      STOP 'SCFDMS'
      RETURN
  600 FORMAT(//1X,'SPARSE DENSITY MATRIX SEARCH NOT INCLUDED ',
     1            'IN THIS DISTRIBUTION. SORRY.')
      END
