      SUBROUTINE SCROSS (ARRAY,LM5,ICALL,SCFCAL)
C     *
C     CONTROL ROUTINE FOR MULTI-SURFACE SINGLE-POINT CALCULATIONS.
C     *
C     NOTATION. I=INPUT, O=OUTPUT, S=SCRATCH.
C     ARRAY     AVAILABLE BUFFER (S).
C     LM5       DIMENSION OF ARRAY (I).
C     ICALL     CONTROL AND ERROR FLAG (I,O).
C     SCFCAL    EXTERNAL ROUTINE FOR ENERGY EVALUATION (I).
C     *
C     ICALL DEFINES THE TYPE OF CALCULATION IN SUBROUTINE SCF.
C     SEE SUBROUTINE SCF FOR THE LIST OF POSSIBLE VALUES.
C     SEE SUBROUTINE SCFMUL FOR SPECIAL CONVENTIONS.
C     *
C     ICALL  ALSO SERVES AS AN ERROR FLAG FOR SUBROUTINE SCFCAL.
C      -1    RETURNED FROM SCFCAL IF THERE IS NO SCF CONVERGENCE
C     *
      USE LIMIT, ONLY: LM1, LMV, LM1M, LMPROP, LMSTAT, LMGRD, LMNAC
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      EXTERNAL SCFCAL
      COMMON
     ./ATOMS / NUMAT,NAT(LM1),NFIRST(LM1),NLAST(LM1)
     ./INOPT2/ IN2(300)
     ./NBFILE/ NBF(20)
      DIMENSION ARRAY(LM5)
      DIMENSION VXYZ(3,LM1+LM1M),CMASS(LM1+LM1M)
      DIMENSION IMASS(LM1)
C *** FILE NUMBERS.
      NB6    = NBF(6)
C *** INPUT OPTIONS.
      IFORM  = IN2(  5)
      NUMATM = IN2(120)
      ICROSS = IN2(160)
      KMASS  = IN2(205)
C *** INITIALIZATION.
      N      = NUMAT+NUMATM
C *** CALL ROUTINES FOR DIFFERENT TASKS.
      IF(ICROSS.EQ.1 .OR. ICROSS.EQ.2 .OR. ICROSS.EQ.7) THEN
         CALL MULSTA (ARRAY,LM5,ICALL,SCFCAL)
      ELSE IF(ICROSS.GE.3 .AND. ICROSS.LE.5) THEN
         CALL CONINT (ARRAY,LM5,ICALL,SCFCAL)
      ELSE IF(ICROSS.EQ.6) THEN
C        WRITE(NB6,*)
C        WRITE(NB6,*)"Set CIDIR=3"
C        IN2(144) = 3
C        WRITE(NB6,*)
         CALL ISOMAS(KMASS,IMASS,NUMAT,NAT,-5,IFORM,AMSUM)
         CALL DYNAM (ARRAY,LM5,ICALL,SCFCAL)
      ENDIF
      RETURN
      END
