name: Pre-commit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: changing the directroy
      run: |
        cd pre_commit_framework
    - name: Analysing the code with pre_commit_framework
      working-directory: ./pre_commit_framework
      run: |
        pre-commit run --all-files
